export const FETCH_REG_INPUTS = 'BBB/REGISTRYINPUTS/FETCH_REG_INPUTS';
export const FETCH_REG_INPUTS_SUCCESS =
  'BBB/REGISTRYINPUTS/FETCH_REG_INPUTS_SUCCESS';
export const FETCH_REG_INPUTS_FAILURE =
  'BBB/REGISTRYINPUTS/FETCH_REG_INPUTS_FAILURE';
export const CLEAR_ERROR_STATE = 'BBB/REGISTRYINPUTS/CLEAR_ERROR_STATE';
export const REG_INPUTS_STATE_KEY = 'createRegistry';
export const ENTER_VALID_ADDRESS_LBL = 'Please enter a valid address.';

export const OPEN_REGISTRY_MODAL_QUERY_STRING = 'showModal';

export const DEFAULT_REGISTRY = 'BRD';

export const DEFAULT_ERROR_MESSAGE = 'response is not correct';
export const CREATE_REG = 'BBB/CREATEREGISTRY/CREATE_REG';
export const CREATE_REG_SUCCESS = 'BBB/CREATEREGISTRY/CREATE_REG_SUCCESS';

export const RESET_STORE_DATA = 'BBB/CREATEREGISTRY/RESET_STORE_DATA';

export const GET_CO_PROFILE_STATUS = 'BBB/CREATEREGISTRY/GET_CO_PROFILE_STATUS';
export const GET_CO_PROFILE_STATUS_SUCCESS =
  'BBB/CREATEREGISTRY/GET_CO_PROFILE_STATUS_SUCCESS';
export const GET_CO_PROFILE_STATUS_FAILURE =
  'BBB/CREATEREGISTRY/GET_CO_PROFILE_STATUS_FAILURE';
export const RESET_CO_PROFILE_STATUS =
  'BBB/CREATEREGISTRY/RESET_CO_PROFILE_STATUS';
export const RESET_CO_PROFILE_STATUS_SUCCESS =
  'BBB/CREATEREGISTRY/RESET_CO_PROFILE_STATUS_SUCCESS';

export const UPDATE_ADDRESS_QAS_MODAL_CONTACT_VISIBILITY_REGISTRY =
  'BBB/QAS/UPDATE_ADDRESS_QAS_MODAL_CONTACT_VISIBILITY_REGISTRY';

export const UPDATE_ADDRESS_QAS_MODAL_SHIPPING_VISIBILITY_REGISTRY =
  'BBB/QAS/UPDATE_ADDRESS_QAS_MODAL_SHIPPING_VISIBILITY_REGISTRY';

export const UPDATE_ADDRESS_QAS_MODAL_MOVING_VISIBILITY_REGISTRY =
  'BBB/QAS/UPDATE_ADDRESS_QAS_MODAL_MOVING_VISIBILITY_REGISTRY';
export const CLEAR_REGISTRY_RESPONSE =
  'BBB/CREATEREGISTRY/CLEAR_REGISTRY_RESPONSE';
export const CLEAR_CREATE_REGISTRY = 'BBB/CREATEREGISTRY/CLEAR_CREATE_REGISTRY';

export const FETCH_QUIZ_MODAL = 'BBB/CREATEREGISTRY/FETCH_QUIZ_MODAL';
export const SET_SCROLL_POSITION = 'BBB/CREATEREGISTRY/SET_SCROLL_POSITION';
export const CLEAR_QUIZ_MODAL = 'BBB/CREATEREGISTRY/CLEAR_QUIZ_MODAL';

export const CLEAR_REGISTRY_VER_TYPE =
  'BBB/CREATEREGISTRY/CLEAR_CREATE_REGISTRY_VER_TYPE';

export const CREATE_REGISTRY_TEALIUM_ACTION = 'create registry';

export const REGISTRY_TEALIUM_PAGE = 'Registry';
export const TEALIUM_CREATE_REGISTRY = 'create registry';
export const TEALIUM_CREATE_REGISTRY_PAGENAME_BREADCRUMB =
  'Registry Create Page';

export const UPDATE_PASSWORD_COMPONENT = 'Update Password Component';
export const UPDATE_SUBMIT_STATE = 'Update Submit State';

export const FORMDATA_EXTEND_PROFILE_STATE_KEY =
  'createRegistryExtendProfileFormData';
export const FORMDATA_REGISTER_LOGIN_STATE_KEY =
  'createRegistryRegisterOrLoginFormData';

export const PAGE_TYPE_NON_LOGGEDIN = 'My Account';
export const NON_LOGGEDIN_PAGENAME_BREADCRUMB =
  'My Account>Log In With Registry Section';
export const GIFT_CARD = '_GiftCard';
export const SET_FORM_REG_TYPE = 'SET_FORM_REG_TYPE';
