export const SELECT_COLLEGE_STATE_KEY = 'selectCollegeStateKey';
export const FETCH_COLLEGE_LIST = 'FETCH_COLLEGE_LIST';
export const FETCH_COLLEGE_LIST_SUCCESS = 'FETCH_COLLEGE_LIST_SUCCESS';
export const FETCH_COLLEGE_LIST_ERROR = 'FETCH_COLLEGE_LIST_ERROR';
