export const SET_FAVORITE_STOREID = 'BBB/REGISTRYFAVSTORE/FAVSTOREID';
export const REMOVE_FAVORITE_STOREID = 'BBB/REGISTRYFAVSTORE/REMOVEFAVSTOREID';
export const SET_FAV_STORE_KEY = 'favStore';
export const SET_FAV_STOREID_KEY = 'favStoreId';
