export const REGISTRY_QUICK_PICKS_COLLECTION_STATE_KEY =
  'registryQuickPicksCollection';

export const BASE = 'BBB/Registry/QuickPicksLanding/Collection';

export const FETCH_QUICK_PICKS_COLLECTION = `${BASE}/FETCH_QUICK_PICKS_COLLECTION`;

export const SET_QUICK_PICKS_COLLECTION = `${BASE}/SET_QUICK_PICKS_COLLECTION`;

export const RESET_QUICK_PICKS_COLLECTION = `${BASE}/RESET_QUICK_PICKS_COLLECTION`;

export const FETCH_QUICK_PICKS_COLLECTION_ERROR = `${BASE}/FETCH_QUICK_PICKS_COLLECTION_ERROR`;

export const ADD_SELECTED_ITEMS_TO_REGISTRY = `${BASE}/ADD_SELECTED_ITEMS_TO_REGISTRY`;

export const SELECT_PRODUCTS = `${BASE}/SELECT_PRODUCTS`;

export const ADD_ITEM_ACTIVE_REGISTRY = `${BASE}/ADD_ITEM_ACTIVE_REGISTRY`;

export const SET_TOAST_NOTIFICATION = `${BASE}/SET_TOAST_NOTIFICATION`;

export const DISPLAY_TOAST_NOTIFICATION = `${BASE}/DISPATCH_TOAST_NOTIFICATION`;

export const UPDATE_PRODUCT_QTY = `${BASE}/UPDATE_PRODUCT_QTY`;

export const TEALIUM_PAGE_INFO = {
  page_type: 'My Account',
  page_name: 'add selected items to registry',
};
