import { getRegistryTeamliumInfo } from '../registryTealiumSelectors';

describe('Populating Registry Details on page load in Json Object for Tealium', () => {
  let registryData;
  let categoryBuckets;

  it("Page Load event for registry landing page 'getRegistryTeamliumInfo", () => {
    registryData = {
      categoryForRegistry: [
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10003',
            catImage: '/images/home/popcats_dinnerware_114508resize.jpg',
            catName: 'FINE DINING & GIFTWARE',
            catSeoUrl: '/category/fine-dining-giftware/10003/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'FINE DINING & GIFTWARE',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10548',
            catImage: '/images/home/popcat_lighting_04032014.jpg',
            catName: 'LIGHTING',
            catSeoUrl: '/category/home-decor/lighting/10548/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'LIGHTING',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10546',
            catImage: null,
            catName: 'FURNITURE',
            catSeoUrl: null,
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'FURNITURE',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10004',
            catImage: '/images/home/HomeDecor_May_2016_Popcat.jpg',
            catName: 'HOME DÉCOR',
            catSeoUrl: '/category/home-d-cor/10004/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'HOME DÉCOR',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10545',
            catImage: '/images/home/HomeDecor_May_2016_Popcat.jpg',
            catName: 'FRAMES',
            catSeoUrl: '/category/home-decor/frames-albums/10545/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'FRAMES',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10005',
            catImage: '/images/home/PopCatQ12016_Storage.jpg',
            catName: 'CLEANING & ORGANIZATION',
            catSeoUrl: '/category/cleaning-organization/10005/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'CLEANING & ORGANIZATION',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10005',
            catImage: '/images/home/PopCatQ12016_Storage.jpg',
            catName: 'VACUUMS & GARMENT CARE',
            catSeoUrl: '/category/vacuums-garment-care/10005/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'VACUUMS & GARMENT CARE',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '13109',
            catImage:
              '/images/home/popcatimg_20170310_bedding_BBBY-US.jpg$other$',
            catName: 'BASIC LINENS',
            catSeoUrl: '/category/bedding/bedding-basics/13109/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'BASIC LINENS',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10001',
            catImage:
              '/images/home/popcatimg_20170310_bedding_BBBY-US.jpg$other$',
            catName: 'LINEN ACCESSORIES',
            catSeoUrl: '/category/linen-accessories/10001/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'LINEN ACCESSORIES',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10001',
            catImage:
              '/images/home/popcatimg_20170310_bedding_BBBY-US.jpg$other$',
            catName: 'BEDDING',
            catSeoUrl: '/category/bedding/10001/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'BEDDING',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '13432',
            catImage: '/images/home/popcatimg_20170310_bath_BBBY-US.jpg$other$',
            catName: 'BATH ACCESSORIES',
            catSeoUrl: '/category/bath-accessories/13432/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'BATH ACCESSORIES',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '13434',
            catImage: '/images/home/popcats_bath.jpg',
            catName: 'BATH TOWELS',
            catSeoUrl: '/category/bath/bath-towels-rugs/bath-towels/13434/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'BATH TOWELS',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10536',
            catImage: '/images/home/popcats_dinnerware_114508resize.jpg',
            catName: 'KITCHEN LINENS',
            catSeoUrl: '/category/dining/table-linens/10536/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'KITCHEN LINENS',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10519',
            catImage:
              '/images/home/popcatimg_20170310_Kitchen_BBBY-US.jpg$other$',
            catName: 'CUTLERY',
            catSeoUrl: '/category/kitchen/knives-cutlery/10519/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'CUTLERY',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10518',
            catImage: '/images/home/popcats_cookware_18489384resize.jpg',
            catName: 'COOKWARE',
            catSeoUrl: '/category/kitchen/cookware/10518/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'COOKWARE',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '12053',
            catImage: '/images/home/popcat_coffee_q3.JPG',
            catName: 'KITCHEN ELECTRICS',
            catSeoUrl: '/category/kitchen/coffee-tea/coffee-makers/12053/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'KITCHEN ELECTRICS',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10002',
            catImage:
              '/images/home/popcatimg_20170310_Kitchen_BBBY-US.jpg$other$',
            catName: 'BASIC HOUSEWARE',
            catSeoUrl: '/category/basic-houseware/10002/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'BASIC HOUSEWARE',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10003',
            catImage: '/images/home/popcats_dinnerware_114508resize.jpg',
            catName: 'TABLETOP',
            catSeoUrl: '/category/tabletop/10003/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'TABLETOP',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: '10580',
            catImage: 'images/registry/other_20130116_reglanding_luggage.jpg',
            catName: 'LUGGAGE',
            catSeoUrl: '/category/more/luggage/10580/',
            recommandedLinks: [],
            recommendedCatFlag: true,
          },
          catgoryName: 'LUGGAGE',
        },
        {
          categoryDetail: {
            addItemFlag: true,
            catId: null,
            catImage: null,
            catName: 'OTHER',
            catSeoUrl: null,
            recommandedLinks: [],
            recommendedCatFlag: false,
          },
          catgoryName: 'OTHER',
        },
      ],
      coRegOwner: false,
      count: 13,
      emailOptIn: -1,
      ephCategoryBuckets: null,
      error: null,
      errorCode: null,
      errorExist: false,
      errorMessage: null,
      expandedCategoryId: null,
      favouriteCategoryIdList: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      favouriteCategoryNameList: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      firstRegistry: false,
      inStockCategoryBuckets: null,
      inStockEPHCategoryBuckets: null,
      isListEmpty: null,
      isPOBoxAddress: 'false',
      items: null,
      notInStockCategoryBuckets: null,
      notInStockEPHCategoryBuckets: null,
      other: null,
      outOfStockListFlag: true,
      priceRangeList: null,
      qty: null,
      recommendationCount: [0, 0],
      recommendationSize: 0,
      registryResVO: {
        error: null,
        importedAsReg: false,
        registryId: 0,
        registrySearchVO: null,
        registrySummaryVO: {
          activeRegistryHasPoBoxAddress: false,
          addrSubType: null,
          allowedToScheduleAStoreAppointment: true,
          bridalToolkitToken: null,
          checklistName: null,
          coRegistrantEmail: null,
          coRegistrantFirstName: 'Asd',
          coRegistrantFirstNameForInitials: null,
          coRegistrantFullName: null,
          coRegistrantLastName: 'Sasa',
          coRegistrantMaidenName: null,
          coownerProfileID: null,
          daysToGo: 3,
          daysToNextCeleb: 0,
          eventCode: null,
          eventDate: '05/31/2018',
          eventDateCanada: null,
          eventDateObject: {
            time: '05/31/2018',
          },
          eventDescription: null,
          eventType: 'Wedding',
          eventVO: {
            babyGender: null,
            babyName: null,
            babyNurseryTheme: null,
            birthDate: null,
            birthDateWS: null,
            college: null,
            eventDate: '20180531',
            eventDateWS: null,
            guestCount: '12',
            showerDate: null,
            showerDateObject: null,
            showerDateWS: null,
          },
          eventYetToCome: true,
          favStoreId: '651',
          futureShippingAddress: null,
          futureShippingDate: null,
          giftPurchased: 0,
          giftRegistered: 14,
          giftRemaining: 14,
          isPublic: '1',
          ownerProfileID: 'DC25409583',
          personalWebsiteToken: null,
          primaryRegistrantEmail: 'testallcoupontypes@feo.com',
          primaryRegistrantFirstName: 'Feohiaasdf',
          primaryRegistrantFirstNameForInitials: null,
          primaryRegistrantFullName: null,
          primaryRegistrantLastName: 'Coupon',
          primaryRegistrantMaidenName: null,
          primaryRegistrantMobileNum: '1111111111',
          primaryRegistrantPrimaryPhoneNum: '1111111111',
          pwsurl: null,
          regTitle: "Feohiaasdf Coupon & Asd Sasa's Wedding Registry",
          regToken: null,
          registrantEmail: 'TESTALLCOUPONTYPES@FEO.COM',
          registrantInitials: null,
          registryId: '543212515',
          registryInfo: 'Feohiaasdf Coupon  :  Asd Sasa  :  543212515',
          registryOwnedByProfile: true,
          registryState: 'post',
          registryType: {
            registryTypeDesc: 'Wedding',
            registryTypeId: null,
            registryTypeIndex: 0,
            registryTypeName: 'BRD',
          },
          schoolId: null,
          serviceRefId: 26,
          shippingAddress: {
            addressLine1: '1076 PARSONS AVENUE',
            addressLine2: null,
            city: 'COLUMBUS',
            company: null,
            country: null,
            firstName: 'Feofeo',
            lastName: 'Coupon',
            poBoxAddress: false,
            primaryPhone: '1111111111',
            qasValidated: false,
            state: 'OH',
            zip: '43206',
          },
          state: 'OH ',
          subType: null,
          totEntries: 0,
        },
        registryToken: null,
        registryVO: {
          affiliateOptIn: null,
          affiliateTag: null,
          checklistname: null,
          coRegBG: null,
          coRegOwner: false,
          coRegistrant: {
            addressSelected: null,
            babyMaidenName: null,
            cellPhone: null,
            coRegEmailFlag: null,
            contactAddress: {
              addressLine1: null,
              addressLine2: null,
              city: null,
              company: null,
              country: null,
              firstName: 'Asd',
              lastName: 'Sasa',
              poBoxAddress: false,
              primaryPhone: null,
              qasValidated: false,
              state: null,
              zip: null,
            },
            email: null,
            firstName: 'Asd',
            lastName: 'Sasa',
            primaryPhone: null,
            profileId: null,
          },
          cookieType: null,
          create: false,
          displayName: null,
          event: {
            babyGender: null,
            babyName: null,
            babyNurseryTheme: null,
            birthDate: null,
            birthDateWS: null,
            college: null,
            eventDate: '20180531',
            eventDateWS: null,
            guestCount: '12',
            showerDate: null,
            showerDateObject: null,
            showerDateWS: null,
          },
          fromPage: null,
          giftPurchased: 0,
          giftRegistered: 14,
          hint: null,
          isPublic: '1',
          listEventType: null,
          listType: null,
          networkAffiliation: 'N',
          numRegAnnouncementCards: 0,
          optInStoreContact: false,
          optInWeddingOrBump: 'N',
          password: null,
          prefCoregContMeth: 0,
          prefCoregContTime: null,
          prefRegContMeth: 0,
          prefRegContTime: null,
          prefStoreNum: '651',
          primaryRegistrant: {
            addressSelected: null,
            babyMaidenName: null,
            cellPhone: '1111111111',
            coRegEmailFlag: null,
            contactAddress: {
              addressLine1: '1076 PARSONS AVENUE',
              addressLine2: null,
              city: 'COLUMBUS',
              company: null,
              country: null,
              firstName: 'Feohiaasdf',
              lastName: 'Coupon',
              poBoxAddress: false,
              primaryPhone: '1111111111',
              qasValidated: false,
              state: 'OH',
              zip: '43206',
            },
            email: 'testallcoupontypes@feo.com',
            firstName: 'Feohiaasdf',
            lastName: 'Coupon',
            primaryPhone: '1111111111',
            profileId: 'DC25409583',
          },
          refStoreContactMethod: 'N',
          regBG: null,
          regInputsForCheckList: null,
          registrantVO: {
            addressSelected: null,
            babyMaidenName: null,
            cellPhone: null,
            coRegEmailFlag: null,
            contactAddress: {
              addressLine1: null,
              addressLine2: null,
              city: null,
              company: null,
              country: null,
              firstName: null,
              lastName: null,
              poBoxAddress: false,
              primaryPhone: null,
              qasValidated: false,
              state: null,
              zip: null,
            },
            email: null,
            firstName: null,
            lastName: null,
            primaryPhone: null,
            profileId: null,
          },
          registryEventType: null,
          registryId: '543212515',
          registryIdWS: 0,
          registryToken: null,
          registryType: {
            registryTypeDesc: 'Wedding',
            registryTypeId: null,
            registryTypeIndex: 0,
            registryTypeName: 'BRD',
          },
          schoolId: null,
          selectedState: null,
          serviceName: null,
          shipping: {
            futureShippingDate: null,
            futureShippingDateWS: null,
            futureshippingAddress: {
              addressLine1: null,
              addressLine2: null,
              city: null,
              company: null,
              country: null,
              firstName: null,
              lastName: null,
              poBoxAddress: false,
              primaryPhone: null,
              qasValidated: false,
              state: null,
              zip: null,
            },
            shippingAddress: {
              addressLine1: '1076 PARSONS AVENUE',
              addressLine2: null,
              city: 'COLUMBUS',
              company: null,
              country: null,
              firstName: 'Feofeo',
              lastName: 'Coupon',
              poBoxAddress: false,
              primaryPhone: '1111111111',
              qasValidated: false,
              state: 'OH',
              zip: '43206',
            },
          },
          signup: null,
          siteId: null,
          status: null,
          surveyQuestionOne: null,
          surveyQuestionTwo: null,
          userAddressList: null,
          userToken: null,
          word: null,
        },
        webServiceError: false,
      },
      showStartBrowsing: null,
      sortSequence: '1',
      webServiceError: false,
    };
    categoryBuckets = [
      {
        catSeoUrl: '/category/baby-kids/nursing-feeding/10570/',
        categoryId: '10570_NURSINGFEEDING',
        displayName: 'NURSING & FEEDING',
        recommandedLinks: [],
        registryItemList: [
          {
            sKUDetailVO: {
              displayName:
                'Boon Twig Grass and Lawn Countertop Drying Rack Accessory in Grey',
              altImageList: [],
              emailStockAlertsEnabled: true,
              shipMsgFlag: true,
              giftWrapEligible: true,
              inCartFlag: false,
              activeFlag: true,
              assemblyTime: '0',
              webOfferedFlag: true,
              skuInStock: true,
              skuId: '40060798',
              eligibleRebates: [],
              customizeCTAFlag: null,
              bopusExcludedForMinimalSku: false,
              customizableRequired: false,
              pricingLabelCode: null,
              parentProdId: '1040060798',
              storeSKU: false,
              commaSepNonShipableStates: null,
              description:
                'This drying rack with a nature motif will add a unique look to your kitchen. The rack is perfect for items of all shapes and sizes, holding them upright for drying.',
              restrictedForIntShip: false,
              skuGiftCard: false,
              hasRebate: false,
              taxStatus: '01',
              personalizationType: 'N',
              dynPriceInfoAlreadyFetched: true,
              vdcOffsetMessage: null,
              eligibleShipMethods: [],
            },
            jdaDeptId: 0,
            upc: null,
            customizedPrice: null,
            personalizationOptionsDisplay: null,
            price: 4.99,
            personlisedPrice: null,
            createTimestamp: null,
            deptSortSeq: 0,
            markedAsFav: false,
            sku: 40060798,
            formattedPersonalizedPrice: '',
            inCartPriceVal: '.00',
            jdaRetailPrice: 0,
          },
        ],
      },
    ];

    let expected = getRegistryTeamliumInfo(registryData, categoryBuckets, {
      averageC1Percentage: 30,
    });
    expect(expected).to.deep.equal({
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_total_items: 14,
      registry_type: 'Wedding',
      shower_celebration_date: '',
      registry_event_date: '05/31/2018',
      registry_checklist_completion: 30,
      registrants_name: 'Feohiaasdf Coupon',
      pagename_breadcrumb: 'Registry View Page',
      navigation_path: 'Registry',
      channel: 'Registry',
      content_pagetype: '',
      crossell_page: 'non-cross sell',
      crossell_product: 'non-cross sell',
      internal_search_term: 'non-search',
      product_finding_method: 'Registry',
      product_pagetype: '',
      product_id: ['1040060798'],
      product_sku_id: ['40060798'],
      product_sku_name: [
        'Boon Twig Grass and Lawn Countertop Drying Rack Accessory in Grey',
      ],
      product_category: ['NURSING & FEEDING'],
      product_subcategory: [],
      product_sub_sub_category: [],
      subnavigation_path: 'Registry',
      internal_campaign: 'non-internal campaign',
      merchandising_main_level: 'non-browse',
      merchandising_category: 'non-browse',
      merchandising_subcategory: 'non-browse',
    });

    expected = getRegistryTeamliumInfo(registryData, categoryBuckets, {
      averageC1Percentage: 30,
    });
    expect(expected).to.deep.equal({
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_total_items: 14,
      registry_type: 'Wedding',
      shower_celebration_date: '',
      registry_event_date: '05/31/2018',
      registry_checklist_completion: 30,
      registrants_name: 'Feohiaasdf Coupon',
      pagename_breadcrumb: 'Registry View Page',
      navigation_path: 'Registry',
      channel: 'Registry',
      content_pagetype: '',
      crossell_page: 'non-cross sell',
      crossell_product: 'non-cross sell',
      internal_search_term: 'non-search',
      product_finding_method: 'Registry',
      product_pagetype: '',
      product_id: ['1040060798'],
      product_sku_id: ['40060798'],
      product_sku_name: [
        'Boon Twig Grass and Lawn Countertop Drying Rack Accessory in Grey',
      ],
      product_category: ['NURSING & FEEDING'],
      product_subcategory: [],
      product_sub_sub_category: [],
      subnavigation_path: 'Registry',
      internal_campaign: 'non-internal campaign',
      merchandising_main_level: 'non-browse',
      merchandising_category: 'non-browse',
      merchandising_subcategory: 'non-browse',
    });
  });
  it("Page Load event for registry landing page registryData is empty'getRegistryTeamliumInfo", () => {
    registryData = undefined;
    const expected = getRegistryTeamliumInfo(registryData, {
      averageC1Percentage: 30,
    });
    expect(expected).to.deep.equal({});
  });
});
