import { getRegistryDataTags } from '../registryOwnerTealiumHelper';

describe('Populating Registry Details on page load in Json Object for Tealium', () => {
  const registryData = {
    categoryBuckets: [
      {
        catgoryName: 'LIGHTING',
        items: null,
      },
      {
        catgoryName: 'HOME DÉCOR',
        items: [
          {
            DSLUpdateable: false,
            aboveLine: false,
            assemblyFees: 0,
            assemblySelected: null,
            colorCD: 0,
            colorDesc: null,
            createTimestamp: {
              time: '05/23/2018 19:35:50',
            },
            customizationDetails: null,
            customizedDoublePrice: null,
            customizedPrice: null,
            deliverySurcharge: 0,
            deptName: null,
            deptSortSeq: 0,
            displayNotifyRegistrantMsg: '',
            ephCatId: null,
            formattedAssemblyFees: '$0',
            formattedCustomizedPrice: '',
            formattedDeliverySurcharge: '$0',
            formattedInCartPriceVal: '$0',
            formattedPersonalizedPrice: '',
            formattedPrice: '$69.99',
            formattedPriceVal: '$69.99',
            formattedTotalDeliveryCharges: '$0',
            formattedTotalPrice: '$69.99',
            giftGiver: false,
            imageURL: null,
            inCartPrice: '0.0',
            inCartPriceVal: '.00',
            isBelowLineItem: 'false',
            itemType: null,
            jdaCatId: null,
            jdaCatName: null,
            jdaDeptId: 0,
            jdaDescription: null,
            jdaRetailPrice: 0,
            lastMaintained: {
              time: '05/23/2018 19:35:50',
            },
            ltlDeliveryServices: null,
            ltlShipMethodDesc: null,
            markedAsFav: false,
            personalisedCode: null,
            personalizationOptionsDisplay: null,
            personalizedImageUrlThumbs: null,
            personalizedImageUrls: null,
            personalizedMobImageUrlThumbs: null,
            personalizedMobImageUrls: null,
            personlisedDoublePrice: null,
            personlisedPrice: null,
            price: 69.99,
            priceVal: 69.99,
            productDescrip: null,
            productURL:
              '/product/ultimate-faux-suede-sofa-protector/3328547?skuId=61613911',
            promoDesc: null,
            promoDescURL: null,
            purchased: false,
            qtyFulfilled: 0,
            qtyPurchased: 0,
            qtyRemaining: 1,
            qtyRequested: 1,
            qtyWebPurchased: 0,
            refNum: null,
            registrantMode: false,
            rowID: 'AAAQf7AATAADEF/AA5',
            sKUDetailVO: {
              activeFlag: true,
              altImageList: [],
              assemblyOffered: false,
              assemblyTime: '0',
              bopusAllowed: true,
              bopusExcludedForMinimalSku: false,
              color: 'GREY',
              commaSepNonShipableStates: null,
              customizableCodes: null,
              customizableRequired: false,
              customizationOffered: false,
              customizeCTAFlag: null,
              description:
                'Effortlessly update the look of your furniture with the Ultimate Sofa Protector. Crafted of soft faux suede with square stitching, this relaxed fit furniture cover offers traditional style and protection from pet hair, spills, and stains.',
              disableFlag: false,
              displayName: 'Ultimate Faux Suede Sofa Protector in Grey',
              displayShipMsg:
                '<a href="/store/static/FreeShipping" class="newOrPopup"><span>\r                      <span class="prod-attrib prod-attrib-free-ship">Free Shipping on Orders Over $29</span> </span> </a>',
              displayURL: 'Ultimate-Faux-Suede-Sofa-Protector-in-Grey',
              dynPriceInfoAlreadyFetched: false,
              dynamicSKUPriceVO: {
                babyIncartFlag: false,
                babyPricingLabelCode: null,
                bbbIncartFlag: false,
                bbbPricingLabelCode: null,
                caIncartFlag: false,
                caPricingLabelCode: null,
                dynamicPriceSKU: false,
                inCartFlag: false,
                mxIncartFlag: false,
                mxPricingLabelCode: null,
                pricingLabelCode: null,
              },
              ecomFulfillment: 'P',
              eligibleRebates: [],
              eligibleShipMethods: [
                {
                  assemblyFees: 0,
                  daysToShip: null,
                  deliverySurcharge: 0,
                  discountedShippingForStandard: null,
                  eddFlag: false,
                  eligibleShipMethod: true,
                  estdShipDurationInDaysHigherLimit: null,
                  estdShipDurationInDaysLowerLimit: null,
                  estimatedDeliveryDate: null,
                  formattedAssemblyFees: '$0',
                  formattedDeliverySurcharge: '$0',
                  formattedShippingCharge: '$0',
                  ltlShipMethod: false,
                  preorderStatus: null,
                  savedInWishlist: null,
                  sddEligiblityStatus: null,
                  sddOptionEnabled: false,
                  shipMethodDescription: 'Standard',
                  shipMethodId: '3g',
                  shippingCharge: 0,
                  singlePreorderDate: null,
                  sortShippingCharge: 0,
                },
                {
                  assemblyFees: 0,
                  daysToShip: null,
                  deliverySurcharge: 0,
                  discountedShippingForStandard: null,
                  eddFlag: false,
                  eligibleShipMethod: true,
                  estdShipDurationInDaysHigherLimit: null,
                  estdShipDurationInDaysLowerLimit: null,
                  estimatedDeliveryDate: null,
                  formattedAssemblyFees: '$0',
                  formattedDeliverySurcharge: '$0',
                  formattedShippingCharge: '$0',
                  ltlShipMethod: false,
                  preorderStatus: null,
                  savedInWishlist: null,
                  sddEligiblityStatus: null,
                  sddOptionEnabled: false,
                  shipMethodDescription: 'Same Day Delivery',
                  shipMethodId: 'SDD',
                  shippingCharge: 0,
                  singlePreorderDate: null,
                  sortShippingCharge: 0,
                },
              ],
              emailStockAlertsEnabled: false,
              freeShipMethods: [],
              giftWrapEligible: false,
              hasRebate: false,
              hasSddAttribute: false,
              inCartFlag: false,
              intlRestricted: false,
              isEcoFeeEligible: false,
              longDescription:
                'Effortlessly update the look of your furniture with the Ultimate Sofa Protector. Crafted of soft faux suede with square stitching, this relaxed fit furniture cover offers traditional style and protection from pet hair, spills, and stains.',
              ltlItem: false,
              nonShippableStates: [],
              onSale: false,
              orderToShipSla: '0',
              parentProdId: '3328547',
              personalizationType: 'N',
              pricingLabelCode: null,
              productSpecs: null,
              restrictedForBopusAllowed: false,
              restrictedForIntShip: false,
              shipMsgFlag: true,
              shippingRestricted: false,
              shippingSurcharge: 0,
              size: 'SOFA',
              skuAttributes: {
                PDPC: [
                  {
                    actionURL: '/store/static/ItemShippedDirectlyFromVendor',
                    attributeDescrip:
                      '<span class="prod-attrib prod-attrib-vendor-ship">Vendor Shipping Details</span>',
                    attributeId: '12_1',
                    attributeName: '12_1',
                    hideAttribute: false,
                    imageURL: null,
                    intlProdAttr: null,
                    placeHolder: 'PDPP,RLP,PDPC',
                    priority: 13,
                    skuAttributeId: null,
                  },
                ],
                PDPP: [
                  {
                    actionURL: '/store/static/ItemShippedDirectlyFromVendor',
                    attributeDescrip:
                      '<span class="prod-attrib prod-attrib-vendor-ship">Vendor Shipping Details</span>',
                    attributeId: '12_1',
                    attributeName: '12_1',
                    hideAttribute: false,
                    imageURL: null,
                    intlProdAttr: null,
                    placeHolder: 'PDPP,RLP,PDPC',
                    priority: 13,
                    skuAttributeId: null,
                  },
                  {
                    actionURL: '/store/static/GiftPackagingUnavailable',
                    attributeDescrip:
                      '<span class="prod-attrib prod-attrib-nogift">Gift Packaging Unavailable</span>',
                    attributeId: '1_85',
                    attributeName: '1_85',
                    hideAttribute: false,
                    imageURL: null,
                    intlProdAttr: null,
                    placeHolder: 'PDPP,RLP',
                    priority: 14,
                    skuAttributeId: null,
                  },
                ],
                RLP: [
                  {
                    actionURL: '/store/static/ItemShippedDirectlyFromVendor',
                    attributeDescrip:
                      '<span class="prod-attrib prod-attrib-vendor-ship">Vendor Shipping Details</span>',
                    attributeId: '12_1',
                    attributeName: '12_1',
                    hideAttribute: false,
                    imageURL: null,
                    intlProdAttr: null,
                    placeHolder: 'PDPP,RLP,PDPC',
                    priority: 13,
                    skuAttributeId: null,
                  },
                  {
                    actionURL: '/store/static/GiftPackagingUnavailable',
                    attributeDescrip:
                      '<span class="prod-attrib prod-attrib-nogift">Gift Packaging Unavailable</span>',
                    attributeId: '1_85',
                    attributeName: '1_85',
                    hideAttribute: false,
                    imageURL: null,
                    intlProdAttr: null,
                    placeHolder: 'PDPP,RLP',
                    priority: 14,
                    skuAttributeId: null,
                  },
                ],
              },
              skuBelowLine: false,
              skuGiftCard: false,
              skuId: '61613911',
              skuImages: {
                altImageList: [],
                anywhereZoomAvailable: false,
                basicImage: '126922261613911p',
                collectionThumbnailImage: null,
                largeImage: '126922261613911p?$478$',
                mediumImage: '126922261613911p?$146$',
                regularImage: null,
                smallImage: '126922261613911p?$146$',
                swatchImage: '1269240237606s',
                thumbnailImage: '126922261613911p?$83$',
                zoomImage: null,
                zoomImageIndex: 0,
              },
              skuInStock: false,
              skuSoldOnline: false,
              storeSKU: false,
              taxStatus: '01',
              upc: '815632017865',
              vdcOffsetMessage: null,
              vdcSKUShipMesage:
                'Ships directly from vendor, delivered in 5 - 10 business days',
              vdcSku: true,
              webOfferedFlag: true,
              zoomAvailable: true,
            },
            shipMethodUnsupported: false,
            sku: 61613911,
            skuAttributes: null,
            smallDesc: null,
            totalDeliveryCharges: 0,
            totalPrice: 69.99,
            upc: null,
          },
        ],
      },
      {
        catgoryName: 'FRAMES',
        items: null,
      },
    ],
    favouriteCategoryIdList: [
      '10003',
      '10546',
      '10004',
      '12053',
      '10002',
      'OtherCat-Id',
    ],
    favouriteCategoryNameList: [
      'FINE DINING & GIFTWARE',
      'FURNITURE',
      'HOME DÉCOR',
      'KITCHEN ELECTRICS',
      'BASIC HOUSEWARE',
      'OTHER',
    ],
    registryResVO: {
      registrySummaryVO: {
        eventDate: '05/31/2018',
        eventType: 'Wedding',
        eventVO: {
          showerDateObject: null,
        },
        giftRegistered: 14,
        primaryRegistrantFirstName: 'Feohiaasdf',
        primaryRegistrantLastName: 'Coupon',
        registryId: '543212515',
        registryType: {
          registryTypeDesc: 'Wedding',
        },
        schoolId: null,
        serviceRefId: 26,
        shippingAddress: {
          addressLine1: '1076 PARSONS AVENUE',
          addressLine2: null,
          city: 'COLUMBUS',
          company: null,
          country: null,
          firstName: 'Feofeo',
          lastName: 'Coupon',
          poBoxAddress: false,
          primaryPhone: '1111111111',
          qasValidated: false,
          state: 'OH',
          zip: '43206',
        },
        state: 'OH ',
        subType: null,
        totEntries: 0,
      },
    },
  };

  it("Page Load event for registry landing page 'getRegistryDataTags", () => {
    const expected = getRegistryDataTags(registryData);
    expect(expected).to.deep.equal({
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_total_items: 14,
      registry_type: 'Wedding',
      shower_celebration_date: '',
      registry_event_date: '05/31/2018',
      registrants_name: 'Feohiaasdf Coupon',
    });
  });

  it("should thankYouListSurpriseData 'getRegistryDataTags", () => {
    const thankYouListSurpriseData = {
      content: {
        data: 'some data',
      },
    };
    const expected = getRegistryDataTags(
      registryData,
      thankYouListSurpriseData
    );
    expect(expected).to.deep.equal({
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_total_items: 14,
      registry_type: 'Wedding',
      shower_celebration_date: '',
      registry_event_date: '05/31/2018',
      registrants_name: 'Feohiaasdf Coupon',
      registry_tab_name: 'Thank You List',
    });
  });

  it("should set registry_favorite_categories_id 'getRegistryDataTags", () => {
    registryData.favouriteCategoryIdList = null;
    registryData.favouriteCategoryNameList = null;
    const expected = getRegistryDataTags(registryData);
    expect(expected).to.deep.equal({
      registry_favorite_categories_id: [],
      registry_favorite_categories_name: [],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_total_items: 14,
      registry_type: 'Wedding',
      shower_celebration_date: '',
      registry_event_date: '05/31/2018',
      registrants_name: 'Feohiaasdf Coupon',
    });
  });
});
