import PropTypes from 'prop-types';

const propTypes = {
  labels: PropTypes.object,
  getRegistryOwnerFirstCategory: PropTypes.func,
  getItemsByPrice: PropTypes.func,
  switchConfig: PropTypes.object,
  selectedFilters: PropTypes.object,
  storeDetails: PropTypes.object,
  getHeaderLayout: PropTypes.bool,
  landingZip: PropTypes.object,
  saveLandingZip: PropTypes.func,
  onPickupInStoreButtonClick: PropTypes.bool,
  isFetching: PropTypes.bool,
  isPickupInStoreModalOpen: PropTypes.bool,
  updateGiftData: PropTypes.func,
  getThankYouList: PropTypes.func,
  registryData: PropTypes.object,
  updateInteractiveCheckList: PropTypes.func,
  makeReviewYourProductsConfig: PropTypes.object,
  getUpdatedCategoryData: PropTypes.func,
  fireTealiumAction: PropTypes.func,
  switchConfigGlobal: PropTypes.object,
  maxItemInRegToShowQuickAdd: PropTypes.number,
  closeOtherOpenModaOnInactiveModal: PropTypes.func,
  initiateInactivityModal: PropTypes.func,
  makeActiveRegistryCall: PropTypes.func,
  updateFilterCount: PropTypes.func,
  filteredItemsCount: PropTypes.number,
  changeFilter: PropTypes.func,
  filter: PropTypes.any,
  isFiltered: PropTypes.bool,
  updatedSkuId: PropTypes.string,
  emptyStoreData: PropTypes.func,
  isMobile: PropTypes.bool,
  variation: PropTypes.string,
  quickItemAddedTS: PropTypes.string,
  isAddToRegistryFetching: PropTypes.bool,
  registryOwnerFirstCategoryList: PropTypes.array,
  updateFilterItemCount: PropTypes.fun,
  track: PropTypes.func,
  onResetFiltersAndSort: PropTypes.func,
  isBopisFeatureEnable: PropTypes.bool,
  selectedCheckboxFilter: PropTypes.string,
  updateBopisCheckBoxState: PropTypes.func,
  isDiaperFundEnable: PropTypes.bool,
};

export default propTypes;
