export const BABY_SOCIAL_RECOMMENDATIONS = 'babySocialRecommendations';
export const SOCIAL_RECOMMENDATION_REGISTRY_BANNER =
  'socialRecommendationRegistryBanner';
export const GUIDE_AND_TOOLS = 'guideAndTools';
export const PRODUCT_FINDING_METHOD = 'Registry Recommendations';
export const PRIVATE_REGISTRY_MESSAGE = '';
export const SOCIAL_RECOMMANDATION_FORM_DATA = 'socialRecommendationFormData';
export const REGISTRY_BUILD_CTA_PANEL = 'registryBuildCTAPanel';
export const NEED_HELP_REFERRED_CONTENT_KEY = 'needHelp';

export const SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK =
  'BBB/SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK';
export const SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_SUCCESS =
  'BBB/SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_SUCCESS';
export const SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_ERROR =
  'BBB/SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_ERROR';
