import PropTypes from 'prop-types';

export const propTypes = {
  isMobile: PropTypes.bool,
  getWarrantyInfo: PropTypes.object,
  getPerfectGift: PropTypes.object,
  getHelp: PropTypes.object,
  bookAppointment: PropTypes.bool,
  liveChat: PropTypes.bool,
  registryData: PropTypes.object,
  labels: PropTypes.object,
  registryFirstCategoryList: PropTypes.array,
  registryOosCategoryList: PropTypes.object,
  tilesView: PropTypes.string,
  inStockCategoryBuckets: PropTypes.string,
  filter: PropTypes.string,
  setBuyOffContext: PropTypes.func,
  registryId: PropTypes.string,
  dateSortedfirstCategoryList: PropTypes.array,
  isItemsFetching: PropTypes.bool,
  isSortedFetching: PropTypes.bool,
  isFetching: PropTypes.bool,
  searchRegistryUrl: PropTypes.string,
  isFiltered: PropTypes.bool,
  akamaiHeader: PropTypes.object,
  saveLandingZip: PropTypes.func,
  isFilterItemReady: PropTypes.bool,
  fireTealiumAction: PropTypes.func,
  switchConfig: PropTypes.object,
  dynamicContentState: PropTypes.object,
  dateSortedOosCategoryList: PropTypes.object,
  displayDiscountedPriceKey: PropTypes.bool,
  selectedDropdownOption: PropTypes.string,
  storeDetails: PropTypes.object,
  handleChangePickupInStore: PropTypes.func,
  handleBopisCheckboxChange: PropTypes.func,
  selectedCheckboxFilter: PropTypes.string,
};

export const renderFacetsCheckboxProps = {
  labels: PropTypes.object,
  storeDetails: PropTypes.object,
  selectedCheckboxFilter: PropTypes.bool,
  isMobile: PropTypes.bool,
  handleBopisCheckboxChange: PropTypes.func,
  handleChangePickupInStore: PropTypes.func,
  bopisStoreDetail: PropTypes.object,
};
