/**
 * RegistryAnalyzer Constants
 */

export const FETCH_REGISTRY_ANALYZER_DATA =
  'BBB/REGISTRY/FETCH_REGISTRY_ANALYZER_DATA';
export const FETCH_REGISTRY_ANALYZER_DATA_SUCCESS =
  'BBB/REGISTRY/FETCH_REGISTRY_ANALYZER_DATA_SUCCESS';
export const FETCH_REGISTRY_ANALYZER_DATA_ERROR =
  'BBB/REGISTRY/FETCH_REGISTRY_ANALYZER_DATA_ERROR';

export const REGISTRY_ANALYZER_STATE_KEY = 'registryAnalyzer';
export const REGISTRY_DETAILS_STATE_KEY = 'registryDetails';
