export const COPY_REGISTRY = 'BBB/CopyRegistry/COPY_REGISTRY';
export const FETCH_COPY_REGISTRY_SUCCESS =
  'BBB/CopyRegistry/FETCH_COPY_REGISTRY_SUCCESS';
export const FETCH_COPY_REGISTRY_ERROR =
  'BBB/DASHBOARD/FETCH_COPY_REGISTRY_ERROR';
export const COPY_SUCCESS_STATE_KEY = 'registryIsCopied';
export const RESET_COPY_REGISTRY_RESPONSE =
  'BBB/COPY_REGISTRY/RESET_COPY_REGISTRY_RESPONSE';
export const DEFAULT_ERROR_MESSAGE = 'response is not correct';

export const WARRANTY_INFO_REFERRED_CONTENT_KEY = 'warrantyInfo';
export const NEED_HELP_REFERRED_CONTENT_KEY = 'needHelp';
export const PERFECT_GIFT_REFERRED_CONTENT_KEY = 'perfectGift';
export const FETCH_FIRST_CATEGORY = 'BBB/GiftGiver/FETCH_FIRST_CATEGORY';
export const FETCH_FIRST_CATEGORY_SUCCESS =
  'BBB/GiftGiver/FETCH_FIRST_CATEGORY_SUCCESS';
export const FETCH_FIRST_CATEGORY_ERROR =
  'BBB/GiftGiver/FETCH_FIRST_CATEGORY_ERROR';
export const FETCH_OTHER_CATEGORIES_ERROR =
  'BBB/GiftGiver/FETCH_OTHER_CATEGORIES_ERROR';
export const FETCH_OTHER_CATEGORIES_SUCCESS =
  'BBB/GiftGiver/FETCH_OTHER_CATEGORIES_SUCCESS';
export const FETCH_OTHER_CATEGORIES = 'BBB/GiftGiver/FETCH_OTHER_CATEGORIES';
export const FETCH_OOS_CATEGORIES_ERROR =
  'BBB/GiftGiver/FETCH_OOS_CATEGORIES_ERROR';
export const FETCH_OOS_CATEGORIES_SUCCESS =
  'BBB/GiftGiver/FETCH_OOS_CATEGORIES_SUCCESS';
export const FETCH_OOS_CATEGORIES = 'BBB/GiftGiver/FETCH_OOS_CATEGORIES';

export const BUYOFF_CONTEXT_STATE_KEY = 'buyoffcontext';
export const GIFT_GIVER_STATE_KEY = 'giftGiver';
export const SET_BUYOFF_CONTEXT = 'BBB/buyoff/context/SET_BUYOFF_CONTEXT';
export const SET_BUYOFF_CONTEXT_VALUE =
  'BBB/buyoff/context/SET_BUYOFF_CONTEXT_VALUE';
export const SET_BUYOFF_CONTEXT_ERROR =
  'BBB/buyoff/context/SET_BUYOFF_CONTEXT_ERROR';
export const BARCODE_MODAL_TEXT_KEY = 'barcodeModaltext';
export const RESET_IS_ITEM_FETCHING = 'BBB/UPDATE/RESET_IS_ITEM_FETCHING';
export const SET_FACET_DATA = 'BBB/SET_FACET_DATA';
export const BOPIS_CHECK_BOX = 'BBB/UPDATE/BOPIS_CHECK_BOX';
export const GUEST_VIEWER_STATE_KEY = 'GuestViewer';
export const REGISTRY_OWNER_ITEMS_STATE_KEY = 'registryOwnerItems';
export const TEALIUM_PAGE_INFO = {
  page_type: 'Registry',
  page_name: 'email registry',
};
export const DISPLAY_DISCOUNTED_PRICE_KEY = 'displayDiscountedPrice';
export const REGISTRY_OWNER_STATE_KEY = 'RegistryOwner';
export const BOPIS_GUEST_CHECKBOX = 'BOPIS_GUEST_CHECKBOX';
