export const FETCH_REGISTRY_RECOMMENDATIONS =
  'BBB/REGISTRY/FETCH_REGISTRY_RECOMMENDATIONS';

export const FETCH_REGISTRY_RECOMMENDER_SUMMARY =
  'BBB/REGISTRY/FETCH_REGISTRY_RECOMMENDER_SUMMARY';
export const FETCH_REGISTRY_RECOMMENDER_SUMMARY_ERROR =
  'BBB/REGISTRY/FETCH_REGISTRY_RECOMMENDER_SUMMARY_ERROR';
export const FETCH_REGISTRY_RECOMMENDER_SUMMARY_SUCCESS =
  'BBB/REGISTRY/FETCH_REGISTRY_RECOMMENDER_SUMMARY_SUCCESS';
export const FETCH_REGISTRY_RECOMMENDATIONS_ERROR =
  'BBB/REGISTRY/FETCH_REGISTRY_RECOMMENDATIONS_ERROR';
export const FETCH_REGISTRY_RECOMMENDATIONS_SUCCESS =
  'BBB/REGISTRY/FETCH_REGISTRY_RECOMMENDATIONS_SUCCESS';
export const REGISTRY_RECOMMENDATIONS_STATE_KEY = 'registryRecommendations';
export const REGISTRY_DETAILS_STATE_KEY = 'registryDetails';
export const TEXT_MY_ITEM = 'My Items';
export const SAVE_EMAIL_FREQUENCY = 'BBB/REGISTRY/SAVE_EMAIL_FREQUENCY';
export const FETCH_REGISTRY_RECOMMENDATIONS_DATE_SORTED =
  'BBB/REGISTRY/FETCH_REGISTRY_RECOMMENDATIONS_DATE_SORTED';

export const MAY_BE_LATER = 'BBB/REGISTRY/MAY_BE_LATER';
export const MAY_BE_LATER_SUCCESS = 'BBB/REGISTRY/MAY_BE_LATER_SUCCESS';
export const MAY_BE_LATER_ERROR = 'BBB/REGISTRY/MAY_BE_LATER_ERROR';
export const INVITE_MORE_FRIENDS_FAMILY = 'inviteMoreFriendandFamily';
export const FETCH_EDIT_REGISTRY_DATA = 'BBB/EditRegistry/FetchData';
export const SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK =
  'BBB/REGISTRY/SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK';
export const SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_SUCCESS =
  'BBB/REGISTRY/SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_SUCCESS';
export const SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_ERROR =
  'BBB/REGISTRY/SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_ERROR';
export const SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_RESET =
  'BBB/REGISTRY/SOCIAL_RECOMMENDATION_BLOCK_UNBLOCK_RESET';
