export const FETCH_EDIT_REGISTRY_DATA = 'BBB/EditRegistry/FetchData';
export const FETCH_EDIT_REGISTRY_DATA_SUCCESS = 'BBB/EditRegistry/Success';
export const FETCH_EDIT_REGISTRY_DATA_ERROR = 'BBB/EditRegistry/Error';
export const CLEAR_EDIT_REGISTRY_DATA = 'BBB/EditRegistry/Clear';
export const EDIT_REGISTRY_DETAILS_STATE_KEY = 'editRegistryDetails';

export const UPDATE_ADDRESS_QAS_MODAL_CONTACT_VISIBILITY_EDIT_REGISTRY =
  'BBB/QAS/UPDATE_ADDRESS_QAS_MODAL_CONTACT_VISIBILITY_EDIT_REGISTRY';

export const UPDATE_ADDRESS_QAS_MODAL_SHIPPING_VISIBILITY_EDIT_REGISTRY =
  'BBB/QAS/UPDATE_ADDRESS_QAS_MODAL_SHIPPING_VISIBILITY_EDIT_REGISTRY';

export const UPDATE_ADDRESS_QAS_MODAL_MOVING_VISIBILITY_EDIT_REGISTRY =
  'BBB/QAS/UPDATE_ADDRESS_QAS_MODAL_MOVING_VISIBILITY_EDIT_REGISTRY';

export const DAVID_BRIDAL_EDIT_MODAL_CONTENT = 'davidBridalEditModalContent';
export const UPDATE_TYM_TAB_CLICK_STATUS =
  'BBB/EditRegistry/UPDATE_TYM_TAB_CLICK_STATUS';
export const TEALIUM_PAGE_INFO = {
  page_name: 'edit registry',
  page_type: 'Registry',
};
export const QUERY_PARAM_SORT = {
  CATEGORY: '1',
  PRICE: '2',
  DATE: '3',
};
export const EDIT_MODAL = 'Group Gifting>Edit Modal';

/* labels */
export const DIAPER_FUND_SECOND_SKU_IMAGE_LBL = '69638538_imageset';
export const DIAPER_FUND_SECOND_SKU_TITLE_LBL = 'Typically lasts 8 months';
export const DIAPER_FUND_THIRD_SKU_TITLE_LBL = 'Typically lasts 12 months';
export const DIAPER_FUND_FIRST_SKU_IMAGE_LBL = '69638537_imageset';
export const DIAPER_FUND_FIRST_SKU_TITLE_LBL = 'Typically lasts 4 months';
export const DIAPER_FUND_THIRD_SKU_IMAGE_LBL = '69638539_imageset';
export const DIAPER_FUND_PRODUCT_IDS_US_BABY_LBL = '5548936,5548937,5548938';
export const DIAPER_FUND_PRODUCT_IDS_LBL = '554,893,655,489,375,000,000';
