export const EDIT_REGISTRY_FORM_DATA_LOCATOR = {
  registryHeading: 'registry-editregistry-popup-header',
  registryFirstName: 'registery-editregistery-firstname',
  registryLastName: 'registery-editregistery-lastname',
  registryBrideOption: 'registery-editregistery-imbride',
  registryGroomOption: 'registery-editregistery-imgroom',
  registryBabyMaidenName: 'registry-maidanName',
  registryEmail: 'registery-editregistery-email',
  registrycoFirstName: 'registery-editregistery-coregfirstname',
  registrycoLastName: 'registery-editregistery-coreglastname',
  registrycoBrideOption: 'registery-editregistery-coregimbride',
  registrycoGroomOption: 'registery-editregistery-coregimgroom',
  registrycoEmail: 'registery-editregistery-coregemail',
  registryStreetAddress: 'registery-editregistery-streetaddress',
  registryAptNo: 'registery-editregistery-aptnumber',
  registryPhoneNumber: 'registery-editregistery-phonenumber',
  registryContactInfoMobile: 'registry-contactInfoMobile',
  registryRegTypePublic: 'registry-editregistry-public-radiobutton',
  registryRegTypePrivate: 'registry-editregistry-private-radiobutton',
  registryRegBigDayDate: 'registery-editregistery-regbigdaydate',
  registryRegFavStore: 'registery-editregistery-regfavstore',
  registryRegSaveBtn: 'registry-editregistry-save-button',
  registryOptionalLink: 'registry-optionallink',
  registryPasswordTextField: 'registry-passwordtextfield',
  registryDifferentAddLink: 'registry-adddeifferentaddresslink',
  registryMovingSoonLink: 'registry-movingsoonlink',
  registryWeddingDateTextField: 'registry-weddingdatetextfield',
  registryEventInfoDate: 'registry-eventInfoEventDate',
  registryShowerDateLink: 'registry-addshowerdatelink',
  registryGuestsField: 'registry-numberofguesttextfield',
  registryCollegeField: 'registry-collegetextfield',
  registryNurseryDecorTheme: 'registery-decortheme',
  registryUnsubscribeCheckBox: 'registry-unsubscribecheckbox',
  registryAdditionalThirdPartyCheckBox: 'registry-additionalthirdpartycheckbox',
  registryEnterZipCodeTextField: 'registry-enterzipcodetextfield',
  registryZipCodeSearchButton: 'registry-zipcodesearchbtn',
  registryRBYROption: 'registry-rbyr-checkbox',
  registryRBYRLearnMore: 'registry-rbyr-learnmore',
};

export const DAVID_BRIDAL_EDIT_MODAL_CONTENT = 'davidBridalEditModalContent';
