/* eslint-disable max-lines */
import { fromJS } from 'immutable';
import gvTealiumInfo from '../guestViewerTealiumInfo';

describe('Populating Cart Details Response in Json Object for Tealium', () => {
  let itemsData;
  let akamiaInfo;
  let favStoreInfo;
  let registryInfo;
  let miniCart;
  beforeEach(() => {
    itemsData = fromJS([
      {
        catSeoUrl: null,
        categoryId: '10002_BASICHOUSEWARE',
        displayName: 'BASIC HOUSEWARE',
        recommandedLinks: null,
        recommendedCatFlag: false,
        registryItemList: [
          {
            promoDesc: null,
            productURL: '/product/mesh-metal-wastebasket/100712?skuId=10217962',
            lastMaintained: null,
            DSLUpdateable: false,
            qtyRemaining: 1,
            personalizedImageUrlThumbs: null,
            personalizedMobImageUrlThumbs: null,
            formattedTotalPrice: '$0',
            assemblySelected: null,
            formattedTotalDeliveryCharges: '$0',
            purchased: false,
            inCartPrice: null,
            colorCD: 0,
            qtyWebPurchased: 0,
            totalPrice: 0,
            totalDeliveryCharges: 0,
            sKUDetailVO: {
              longDescription:
                'The attractive Seville Mesh Metal Wastebasket is both stylish and useful. Featuring solid metal bases and sturdy mesh frames, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
              size: '13.4&quot; X 13.4&quot;',
              ecomFulfillment: 'E',
              displayShipMsg:
                '<a href="/store/static/FreeShipping" class="newOrPopup"><span>\r                      <span class="prod-attrib prod-attrib-free-ship">Free Shipping on Orders Over $29</span> </span> </a>',
              nonShippableStates: [],
              orderToShipSla: '0',
              color: 'BLACK',
              hasSddAttribute: true,
              skuSoldOnline: false,
              onSale: false,
              bopusAllowed: false,
              customizationOffered: false,
              upc: '17641140569',
              vdcSku: false,
              vdcSKUShipMesage: null,
              skuBelowLine: false,
              productSpecs: null,
              shippingRestricted: false,
              customizableCodes: null,
              freeShipMethods: [],
              displayURL: null,
              displayName: 'Mesh Metal Wastebasket in Black',
              altImageList: [],
              emailStockAlertsEnabled: true,
              shipMsgFlag: true,
              giftWrapEligible: true,
              inCartFlag: false,
              activeFlag: true,
              assemblyTime: '0',
              webOfferedFlag: true,
              skuInStock: true,
              disableFlag: false,
              restrictedForBopusAllowed: false,
              skuImages: {
                largeImage: '60664210217962p?$478$',
                mediumImage: '60664210217962p?$146$',
                zoomImage: null,
                zoomImageIndex: 0,
                basicImage: '60664210217962p',
                collectionThumbnailImage: null,
                thumbnailImage: '60664210217962p?$83$',
                altImageList: [],
                smallImage: '60664210217962p?$146$',
                anywhereZoomAvailable: false,
                swatchImage: '1762100712s',
                regularImage: null,
              },
              assemblyOffered: false,
              zoomAvailable: false,
              shippingSurcharge: 0,
              isEcoFeeEligible: false,
              ltlItem: false,
              intlRestricted: false,
              skuId: '10217962',
              eligibleRebates: [],
              customizeCTAFlag: null,
              bopusExcludedForMinimalSku: false,
              customizableRequired: false,
              pricingLabelCode: null,
              parentProdId: '100712',
              storeSKU: false,
              commaSepNonShipableStates: null,
              description:
                'The attractive Seville Mesh Metal Wastebasket is both stylish and useful. Featuring solid metal bases and sturdy mesh frames, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
              restrictedForIntShip: false,
              skuGiftCard: false,
              hasRebate: false,
              taxStatus: '01',
              personalizationType: 'N',
              dynPriceInfoAlreadyFetched: false,
              vdcOffsetMessage: null,
              eligibleShipMethods: [],
            },
            jdaDeptId: 0,
            upc: null,
            customizedPrice: null,
            personalizationOptionsDisplay: null,
            price: 11.99,
            personlisedPrice: null,
            qtyFulfilled: 0,
            jdaCatId: '10002',
            displayNotifyRegistrantMsg: 'D',
            formattedCustomizedPrice: '',
            itemType: '',
            qtyPurchased: 0,
            formattedPrice: '$11.99',
            registrantMode: false,
            isBelowLineItem: 'false',
            promoDescURL: null,
            personalizedMobImageUrls: null,
            personalizedImageUrls: null,
            customizationDetails: null,
            formattedAssemblyFees: '$0',
            deptName: null,
            deliverySurcharge: 0,
            giftGiver: false,
            aboveLine: true,
            ltlShipMethodDesc: null,
            assemblyFees: 0,
            refNum: null,
            ephCatId: '',
            colorDesc: null,
            formattedPriceVal: '$11.99',
            formattedDeliverySurcharge: '$0',
            imageURL: null,
            skuAttributes: null,
            rowID: 'AAAQf7AATAADELSAAp',
            jdaDescription: null,
            ltlDeliveryServices: null,
            personalisedCode: null,
            customizedDoublePrice: null,
            smallDesc: null,
            personlisedDoublePrice: null,
            priceVal: 11.99,
            qtyRequested: 1,
            shipMethodUnsupported: false,
            productDescrip: null,
            formattedInCartPriceVal: '',
            jdaCatName: 'BASIC HOUSEWARE',
            createTimestamp: null,
            deptSortSeq: 0,
            markedAsFav: false,
            sku: 10217962,
            formattedPersonalizedPrice: '',
            inCartPriceVal: null,
            jdaRetailPrice: 0,
          },
          {
            promoDesc: null,
            productURL: '/product/mesh-metal-wastebasket/100712?skuId=11170544',
            lastMaintained: null,
            DSLUpdateable: false,
            qtyRemaining: 1,
            personalizedImageUrlThumbs: null,
            personalizedMobImageUrlThumbs: null,
            formattedTotalPrice: '$0',
            assemblySelected: null,
            formattedTotalDeliveryCharges: '$0',
            purchased: false,
            inCartPrice: null,
            colorCD: 0,
            qtyWebPurchased: 0,
            totalPrice: 0,
            totalDeliveryCharges: 0,
            sKUDetailVO: {
              longDescription:
                'This attractive Seville Mesh Metal Wastebasket is both stylish and useful. Featuring a solid metal base and sturdy mesh frame, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
              size: '13.4&quot; X 13.4&quot;',
              ecomFulfillment: 'E',
              displayShipMsg:
                '<a href="/store/static/FreeShipping" class="newOrPopup"><span>\r                      <span class="prod-attrib prod-attrib-free-ship">Free Shipping on Orders Over $29</span> </span> </a>',
              nonShippableStates: [],
              orderToShipSla: '0',
              color: 'CHROME',
              hasSddAttribute: true,
              skuSoldOnline: false,
              onSale: false,
              bopusAllowed: false,
              customizationOffered: false,
              upc: '17641140576',
              vdcSku: false,
              vdcSKUShipMesage: null,
              skuBelowLine: false,
              productSpecs: null,
              shippingRestricted: false,
              customizableCodes: null,
              freeShipMethods: [],
              displayURL: null,
              displayName: 'Mesh Metal Wastebasket in Chrome',
              altImageList: [],
              emailStockAlertsEnabled: true,
              shipMsgFlag: true,
              giftWrapEligible: false,
              inCartFlag: false,
              activeFlag: true,
              assemblyTime: '0',
              webOfferedFlag: true,
              skuInStock: true,
              disableFlag: false,
              restrictedForBopusAllowed: false,
              skuImages: {
                largeImage: '21546911170544p?$478$',
                mediumImage: '21546911170544p?$146$',
                zoomImage: null,
                zoomImageIndex: 0,
                basicImage: '21546911170544p',
                collectionThumbnailImage: null,
                thumbnailImage: '21546911170544p?$83$',
                altImageList: [],
                smallImage: '21546911170544p?$146$',
                anywhereZoomAvailable: false,
                swatchImage: '1761100712s',
                regularImage: null,
              },
              assemblyOffered: false,
              zoomAvailable: false,
              shippingSurcharge: 0,
              isEcoFeeEligible: false,
              ltlItem: false,
              intlRestricted: false,
              skuId: '11170544',
              eligibleRebates: [],
              customizeCTAFlag: null,
              bopusExcludedForMinimalSku: false,
              customizableRequired: false,
              pricingLabelCode: null,
              parentProdId: '100712',
              storeSKU: false,
              commaSepNonShipableStates: null,
              description:
                'This attractive Seville Mesh Metal Wastebasket is both stylish and useful. Featuring a solid metal base and sturdy mesh frame, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
              restrictedForIntShip: false,
              skuGiftCard: false,
              hasRebate: false,
              taxStatus: '01',
              personalizationType: 'N',
              dynPriceInfoAlreadyFetched: false,
              vdcOffsetMessage: null,
              eligibleShipMethods: [],
            },
            jdaDeptId: 0,
            upc: null,
            customizedPrice: null,
            personalizationOptionsDisplay: null,
            price: 4.99,
            personlisedPrice: null,
            qtyFulfilled: 0,
            jdaCatId: '10002',
            displayNotifyRegistrantMsg: 'D',
            formattedCustomizedPrice: '',
            itemType: '',
            qtyPurchased: 0,
            formattedPrice: '$4.99',
            registrantMode: false,
            isBelowLineItem: 'false',
            promoDescURL: null,
            personalizedMobImageUrls: null,
            personalizedImageUrls: null,
            customizationDetails: null,
            formattedAssemblyFees: '$0',
            deptName: null,
            deliverySurcharge: 0,
            giftGiver: false,
            aboveLine: true,
            ltlShipMethodDesc: null,
            assemblyFees: 0,
            refNum: null,
            ephCatId: '',
            colorDesc: null,
            formattedPriceVal: '$4.99',
            formattedDeliverySurcharge: '$0',
            imageURL: null,
            skuAttributes: null,
            rowID: 'AAAQf7AATAADELSAAo',
            jdaDescription: null,
            ltlDeliveryServices: null,
            personalisedCode: null,
            customizedDoublePrice: null,
            smallDesc: null,
            personlisedDoublePrice: null,
            priceVal: 4.99,
            qtyRequested: 1,
            shipMethodUnsupported: false,
            productDescrip: null,
            formattedInCartPriceVal: '',
            jdaCatName: 'BASIC HOUSEWARE',
            createTimestamp: null,
            deptSortSeq: 0,
            markedAsFav: false,
            sku: 11170544,
            formattedPersonalizedPrice: '',
            inCartPriceVal: null,
            jdaRetailPrice: 0,
          },
          {
            promoDesc: null,
            productURL: '/product/mesh-metal-wastebasket/100712?skuId=43829040',
            lastMaintained: null,
            DSLUpdateable: false,
            qtyRemaining: 1,
            personalizedImageUrlThumbs: null,
            personalizedMobImageUrlThumbs: null,
            formattedTotalPrice: '$0',
            assemblySelected: null,
            formattedTotalDeliveryCharges: '$0',
            purchased: false,
            inCartPrice: null,
            colorCD: 0,
            qtyWebPurchased: 0,
            totalPrice: 0,
            totalDeliveryCharges: 0,
            sKUDetailVO: {
              longDescription:
                'The attractive Mesh Metal Wastebasket is both stylish and useful. Featuring solid metal bases and sturdy mesh frames, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
              size: '13.75&quot; X 11.75&quot;',
              ecomFulfillment: 'E',
              displayShipMsg:
                '<a href="/store/static/FreeShipping" class="newOrPopup"><span>\r                      <span class="prod-attrib prod-attrib-free-ship">Free Shipping on Orders Over $29</span> </span> </a>',
              nonShippableStates: [],
              orderToShipSla: '0',
              color: 'AQUA',
              hasSddAttribute: true,
              skuSoldOnline: false,
              dynamicSKUPriceVO: {
                mxPricingLabelCode: null,
                babyIncartFlag: false,
                caIncartFlag: false,
                babyPricingLabelCode: 'WAS',
                inCartFlag: false,
                dynamicPriceSKU: true,
                bbbIncartFlag: false,
                caPricingLabelCode: 'WAS',
                pricingLabelCode: 'WAS',
                mxIncartFlag: false,
                bbbPricingLabelCode: 'WAS',
              },
              onSale: false,
              bopusAllowed: false,
              customizationOffered: false,
              upc: '17641142266',
              vdcSku: false,
              vdcSKUShipMesage: null,
              skuBelowLine: false,
              productSpecs: null,
              shippingRestricted: false,
              customizableCodes: null,
              freeShipMethods: [],
              displayURL: null,
              displayName: 'Mesh Metal Wastebasket in Aqua',
              altImageList: [],
              emailStockAlertsEnabled: false,
              shipMsgFlag: true,
              giftWrapEligible: true,
              inCartFlag: false,
              activeFlag: true,
              assemblyTime: '0',
              webOfferedFlag: true,
              skuInStock: true,
              disableFlag: false,
              restrictedForBopusAllowed: false,
              skuImages: {
                largeImage: '60017843829040p?$478$',
                mediumImage: '60017843829040p?$146$',
                zoomImage: null,
                zoomImageIndex: 0,
                basicImage: '60017843829040p',
                collectionThumbnailImage: null,
                thumbnailImage: '60017843829040p?$83$',
                altImageList: [],
                smallImage: '60017843829040p?$146$',
                anywhereZoomAvailable: false,
                swatchImage: '600177100712s',
                regularImage: null,
              },
              assemblyOffered: false,
              zoomAvailable: false,
              shippingSurcharge: 0,
              isEcoFeeEligible: false,
              ltlItem: false,
              intlRestricted: false,
              skuId: '43829040',
              eligibleRebates: [],
              customizeCTAFlag: null,
              bopusExcludedForMinimalSku: false,
              customizableRequired: false,
              pricingLabelCode: 'WAS',
              parentProdId: '100712',
              storeSKU: false,
              commaSepNonShipableStates: null,
              description:
                'The attractive Mesh Metal Wastebasket is both stylish and useful. Featuring solid metal bases and sturdy mesh frames, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
              restrictedForIntShip: false,
              skuGiftCard: false,
              hasRebate: false,
              taxStatus: '01',
              personalizationType: 'N',
              dynPriceInfoAlreadyFetched: false,
              vdcOffsetMessage: null,
              eligibleShipMethods: [],
            },
            jdaDeptId: 0,
            upc: null,
            customizedPrice: null,
            personalizationOptionsDisplay: null,
            price: 3.99,
            personlisedPrice: null,
            qtyFulfilled: 0,
            jdaCatId: '10002',
            displayNotifyRegistrantMsg: 'D',
            formattedCustomizedPrice: '',
            itemType: '',
            qtyPurchased: 0,
            formattedPrice: '$3.99',
            registrantMode: false,
            isBelowLineItem: 'false',
            promoDescURL: null,
            personalizedMobImageUrls: null,
            personalizedImageUrls: null,
            customizationDetails: null,
            formattedAssemblyFees: '$0',
            deptName: null,
            deliverySurcharge: 0,
            giftGiver: false,
            aboveLine: true,
            ltlShipMethodDesc: null,
            assemblyFees: 0,
            refNum: null,
            ephCatId: '',
            colorDesc: null,
            formattedPriceVal: '$3.99',
            formattedDeliverySurcharge: '$0',
            imageURL: null,
            skuAttributes: null,
            rowID: 'AAAQf7AATAADELSAAq',
            jdaDescription: null,
            ltlDeliveryServices: null,
            personalisedCode: null,
            customizedDoublePrice: null,
            smallDesc: null,
            personlisedDoublePrice: null,
            priceVal: 3.99,
            qtyRequested: 1,
            shipMethodUnsupported: false,
            productDescrip: null,
            formattedInCartPriceVal: '',
            jdaCatName: 'BASIC HOUSEWARE',
            createTimestamp: null,
            deptSortSeq: 0,
            markedAsFav: false,
            sku: 43829040,
            formattedPersonalizedPrice: '',
            inCartPriceVal: null,
            jdaRetailPrice: 0,
          },
        ],
      },
      {
        registryItemList: [
          {
            promoDesc: null,
            productURL:
              '/product/the-collection-customized-drapery/3330506?skuId=47531338',
            lastMaintained: null,
            DSLUpdateable: false,
            qtyRemaining: 1,
            personalizedImageUrlThumbs:
              '//bbby-test.katori.com/img/bbby/5b4/5b47274683cb21550f8b4659-xs-mod.jpg',
            personalizedMobImageUrlThumbs: null,
            formattedTotalPrice: '$0',
            assemblySelected: '',
            formattedTotalDeliveryCharges: '$0',
            purchased: false,
            inCartPrice: null,
            colorCD: 0,
            qtyWebPurchased: 0,
            totalPrice: 0,
            totalDeliveryCharges: 0,
            sKUDetailVO: {
              longDescription:
                'Create customized curtains for your home with our Collection Customize Drapery. Choose from 250 timeless designs in casual and luxurious fabrics. There are 4 lengths to choose from and panels are available in rod pocket, grommet, and pinch pleats.',
              size: 'NO SIZE',
              ecomFulfillment: 'E',
              displayShipMsg:
                '<a href="/store/static/FreeShipping" class="newOrPopup"><span>\r                      <span class="prod-attrib prod-attrib-free-ship">Free Shipping on Orders Over $29</span> </span> </a>',
              nonShippableStates: [],
              orderToShipSla: '0',
              color: 'MULTI',
              hasSddAttribute: false,
              skuSoldOnline: false,
              dynamicSKUPriceVO: {
                mxPricingLabelCode: null,
                babyIncartFlag: false,
                caIncartFlag: false,
                babyPricingLabelCode: null,
                inCartFlag: false,
                dynamicPriceSKU: false,
                bbbIncartFlag: false,
                caPricingLabelCode: null,
                pricingLabelCode: null,
                mxIncartFlag: false,
                bbbPricingLabelCode: null,
              },
              onSale: false,
              bopusAllowed: true,
              customizationOffered: true,
              upc: '80995590342',
              vdcSku: true,
              vdcSKUShipMesage:
                'Ships directly from vendor, delivered in 5 - 10 business days',
              skuBelowLine: false,
              productSpecs: null,
              shippingRestricted: false,
              customizableCodes: null,
              freeShipMethods: [],
              displayURL: null,
              displayName: 'The Collection Customized Drapery',
              altImageList: [],
              emailStockAlertsEnabled: false,
              shipMsgFlag: true,
              giftWrapEligible: false,
              inCartFlag: false,
              activeFlag: true,
              assemblyTime: '0',
              webOfferedFlag: true,
              skuInStock: true,
              disableFlag: false,
              restrictedForBopusAllowed: false,
              skuImages: {
                largeImage: '98579347531338p?$478$',
                mediumImage: '98579347531338p?$146$',
                zoomImage: null,
                zoomImageIndex: 0,
                basicImage: '98579347531338p',
                collectionThumbnailImage: null,
                thumbnailImage: '98579347531338p?$83$',
                altImageList: [],
                smallImage: '98579347531338p?$146$',
                anywhereZoomAvailable: false,
                swatchImage: null,
                regularImage: null,
              },
              assemblyOffered: false,
              zoomAvailable: false,
              shippingSurcharge: 0,
              isEcoFeeEligible: false,
              ltlItem: false,
              intlRestricted: false,
              skuId: '47531338',
              eligibleRebates: [],
              customizeCTAFlag: null,
              bopusExcludedForMinimalSku: false,
              customizableRequired: true,
              pricingLabelCode: null,
              parentProdId: '3330506',
              storeSKU: false,
              commaSepNonShipableStates: null,
              description:
                'Create customized curtains for your home with our Collection Customize Drapery. Choose from 250 timeless designs in casual and luxurious fabrics. There are 4 lengths to choose from and panels are available in rod pocket, grommet, and pinch pleats.',
              restrictedForIntShip: false,
              skuGiftCard: false,
              hasRebate: false,
              taxStatus: '01',
              personalizationType: 'CR',
              dynPriceInfoAlreadyFetched: true,
              vdcOffsetMessage: null,
              eligibleShipMethods: [],
            },
            jdaDeptId: 0,
            upc: null,
            customizedPrice: null,
            personalizationOptionsDisplay: 'C',
            price: 0.01,
            personlisedPrice: 59.99,
            qtyFulfilled: 0,
            jdaCatId: 'other',
            displayNotifyRegistrantMsg: '',
            formattedCustomizedPrice: '$59.99',
            itemType: 'PER',
            qtyPurchased: 0,
            formattedPrice: '$0.01',
            registrantMode: false,
            isBelowLineItem: 'false',
            promoDescURL: null,
            personalizedMobImageUrls:
              '//bbby-test.katori.com/img/bbby/5b4/5b47274683cb21550f8b4659-md.jpg',
            personalizedImageUrls:
              '//bbby-test.katori.com/img/bbby/5b4/5b47274683cb21550f8b4659-lg-mod.jpg',
            customizationDetails:
              '<br/>Style: Rod Pocket<br/>Dimensions: 50W x 95L<br/>Fabric: Elsina<br/>Fabric Color: Navy',
            formattedAssemblyFees: '$0',
            deptName: null,
            deliverySurcharge: 0,
            giftGiver: false,
            aboveLine: true,
            ltlShipMethodDesc: null,
            assemblyFees: 0,
            refNum: '5b47274683cb21550f8b4659',
            ephCatId: '',
            colorDesc: null,
            formattedPriceVal: '$0.01',
            formattedDeliverySurcharge: '$0',
            imageURL: null,
            skuAttributes: null,
            rowID: 'AAAQjCAAtAAJmDdAAD',
            jdaDescription: null,
            ltlDeliveryServices: '',
            personalisedCode: 'CD',
            customizedDoublePrice: 59.99,
            smallDesc: null,
            personlisedDoublePrice: 59.99,
            priceVal: 0.01,
            qtyRequested: 1,
            shipMethodUnsupported: false,
            productDescrip: null,
            formattedInCartPriceVal: '',
            jdaCatName: 'OTHER',
            createTimestamp: null,
            deptSortSeq: 0,
            markedAsFav: false,
            sku: 47531338,
            formattedPersonalizedPrice: '$59.99',
            inCartPriceVal: null,
            jdaRetailPrice: 0,
          },
          {
            promoDesc: null,
            productURL:
              '/product/smartstuff-trade-genevieve-convertible-crib/3328113?skuId=60731661',
            lastMaintained: null,
            DSLUpdateable: false,
            qtyRemaining: 1,
            personalizedImageUrlThumbs: '',
            personalizedMobImageUrlThumbs: null,
            formattedTotalPrice: '$829.99',
            assemblySelected: 'Y',
            formattedTotalDeliveryCharges: '$70',
            purchased: false,
            inCartPrice: null,
            colorCD: 0,
            qtyWebPurchased: 0,
            totalPrice: 829.99,
            totalDeliveryCharges: 70,
            sKUDetailVO: {
              longDescription:
                'Add clean, sophisticated functionality to your child&#39;s bedroom with the Genevieve Convertible Crib from smartstuff. Embellished with distinctive details and a lavish finish, the crib is easily adjustable to the perfect height and converts into a bed.',
              size: 'CRIB',
              ecomFulfillment: 'P',
              displayShipMsg: null,
              nonShippableStates: [],
              orderToShipSla: '7',
              color: 'WHITE',
              hasSddAttribute: false,
              skuSoldOnline: false,
              dynamicSKUPriceVO: {
                mxPricingLabelCode: null,
                babyIncartFlag: false,
                caIncartFlag: false,
                babyPricingLabelCode: null,
                inCartFlag: false,
                dynamicPriceSKU: false,
                bbbIncartFlag: false,
                caPricingLabelCode: null,
                pricingLabelCode: null,
                mxIncartFlag: false,
                bbbPricingLabelCode: null,
              },
              onSale: false,
              bopusAllowed: true,
              customizationOffered: false,
              upc: '807223928971',
              vdcSku: true,
              vdcSKUShipMesage: null,
              skuBelowLine: false,
              productSpecs: null,
              shippingRestricted: false,
              customizableCodes: null,
              freeShipMethods: [],
              displayURL: null,
              displayName:
                'smartstuff&trade; Genevieve Convertible Crib in White',
              altImageList: [],
              emailStockAlertsEnabled: false,
              shipMsgFlag: false,
              giftWrapEligible: false,
              inCartFlag: false,
              activeFlag: true,
              assemblyTime: '30',
              webOfferedFlag: true,
              skuInStock: true,
              disableFlag: false,
              restrictedForBopusAllowed: false,
              skuImages: {
                largeImage: '127069260731661p?$478$',
                mediumImage: '127069260731661p?$146$',
                zoomImage: null,
                zoomImageIndex: 0,
                basicImage: '127069260731661p',
                collectionThumbnailImage: null,
                thumbnailImage: '127069260731661p?$83$',
                altImageList: [],
                smallImage: '127069260731661p?$146$',
                anywhereZoomAvailable: false,
                swatchImage: null,
                regularImage: null,
              },
              assemblyOffered: true,
              zoomAvailable: false,
              shippingSurcharge: 0,
              isEcoFeeEligible: false,
              ltlItem: true,
              intlRestricted: true,
              skuId: '60731661',
              eligibleRebates: [],
              customizeCTAFlag: null,
              bopusExcludedForMinimalSku: false,
              customizableRequired: false,
              pricingLabelCode: null,
              parentProdId: '3328113',
              storeSKU: false,
              commaSepNonShipableStates: null,
              description:
                'Add clean, sophisticated functionality to your child&#39;s bedroom with the Genevieve Convertible Crib from smartstuff. Embellished with distinctive details and a lavish finish, the crib is easily adjustable to the perfect height and converts into a bed.',
              restrictedForIntShip: false,
              skuGiftCard: false,
              hasRebate: false,
              taxStatus: '01',
              personalizationType: 'N',
              dynPriceInfoAlreadyFetched: false,
              vdcOffsetMessage: null,
              eligibleShipMethods: [],
            },
            jdaDeptId: 0,
            upc: null,
            customizedPrice: null,
            personalizationOptionsDisplay: null,
            price: 759.99,
            personlisedPrice: null,
            qtyFulfilled: 0,
            jdaCatId: 'other',
            displayNotifyRegistrantMsg: '',
            formattedCustomizedPrice: '$0',
            itemType: 'LTL',
            qtyPurchased: 0,
            formattedPrice: '$759.99',
            registrantMode: false,
            isBelowLineItem: 'false',
            promoDescURL: null,
            personalizedMobImageUrls: '',
            personalizedImageUrls: '',
            customizationDetails: '',
            formattedAssemblyFees: '$30',
            deptName: null,
            deliverySurcharge: 40,
            giftGiver: false,
            aboveLine: true,
            ltlShipMethodDesc: 'White Glove Delivery With Assembly',
            assemblyFees: 30,
            refNum: '',
            ephCatId: '',
            colorDesc: null,
            formattedPriceVal: '$759.99',
            formattedDeliverySurcharge: '$40',
            imageURL: null,
            skuAttributes: null,
            rowID: 'AAAQjCAAtAAJmDdAAC',
            jdaDescription: null,
            ltlDeliveryServices: 'LWA',
            personalisedCode: '',
            customizedDoublePrice: 0,
            smallDesc: null,
            personlisedDoublePrice: 0,
            priceVal: 759.99,
            qtyRequested: 1,
            shipMethodUnsupported: false,
            productDescrip: null,
            formattedInCartPriceVal: '',
            jdaCatName: 'OTHER',
            createTimestamp: null,
            deptSortSeq: 0,
            markedAsFav: false,
            sku: 60731661,
            formattedPersonalizedPrice: '$0',
            inCartPriceVal: null,
            jdaRetailPrice: 0,
          },
        ],
      },
    ]);
    akamiaInfo = {
      customer_postal_code: '20001',
    };
    favStoreInfo = {
      favorite_store_id: '42',
    };
    registryInfo = {
      categoryBuckets: null,
      favouriteCategoryIdList: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      favouriteCategoryNameList: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registryResVO: {
        registrySummaryVO: {
          eventDate: '05/31/2018',
          eventType: 'Wedding',
          eventVO: {
            showerDateObject: null,
          },
          giftRegistered: 14,
          primaryRegistrantFirstName: 'Feohiaasdf',
          primaryRegistrantLastName: 'Coupon',
          registryId: '543212515',
          registryType: {
            registryTypeDesc: 'Wedding',
          },
          schoolId: null,
          serviceRefId: 26,
          shippingAddress: {
            addressLine1: '1076 PARSONS AVENUE',
            addressLine2: null,
            city: 'COLUMBUS',
            company: null,
            country: null,
            firstName: 'Feofeo',
            lastName: 'Coupon',
            poBoxAddress: false,
            primaryPhone: '1111111111',
            qasValidated: false,
            state: 'OH',
            zip: '43206',
          },
          state: 'OH ',
          subType: null,
          totEntries: 0,
        },
      },
    };
    miniCart = {
      atgResponse: {
        cart: {
          cartItemCount: '2',
        },
        orderPriceInfoDisplayVO: {
          formattedTotalAmount: '$42',
        },
      },
    };
  });
  const actualdata = {
    brand_id: [],
    brand_name: [],
    call_to_actiontype: 'add to registry',
    cart_total_items: 0,
    cart_total_value: '$42',
    category_id: '',
    crossell_page: 'non-cross sell',
    crossell_product: 'non-cross sell',
    customer_postal_code: '20001',
    device_fingerprint: '',
    favorite_store_id: '42',
    inventory_status: [
      'in stock',
      'in stock',
      'in stock',
      'in stock',
      'in stock',
    ],
    is_ltl_item: [false, false, false, false, true],
    level_of_service: ['', '', '', '', 'White Glove Delivery With Assembly'],
    page_name: 'add to registry',
    page_type: 'Registry',
    pagename_breadcrumb: 'Registry View Page',
    // prettier-ignore
    personalization_type: [ undefined, undefined, undefined, 'Personalization', undefined ],
    product_category: [],
    product_has_personalization: ['false', 'false', 'false', 'true', 'false'],
    product_id: ['100712', '100712', '100712', '3330506', '3328113'],
    product_image_name: [
      'Mesh Metal Wastebasket in Black',
      'Mesh Metal Wastebasket in Chrome',
      'Mesh Metal Wastebasket in Aqua',
      'The Collection Customized Drapery',
      'smartstuff&trade; Genevieve Convertible Crib in White',
    ],
    product_image_url: [
      '60664210217962p?$146$',
      '21546911170544p?$146$',
      '60017843829040p?$146$',
      '98579347531338p?$146$',
      '127069260731661p?$146$',
    ],
    product_name: [
      'Mesh Metal Wastebasket in Black',
      'Mesh Metal Wastebasket in Chrome',
      'Mesh Metal Wastebasket in Aqua',
      'The Collection Customized Drapery',
      'smartstuff&trade; Genevieve Convertible Crib in White',
    ],
    product_price: [11.99, 4.99, 3.99, 0.01, 759.99],
    product_quantity: [1, 1, 1, 1, 1],
    product_sku_id: [
      '10217962',
      '11170544',
      '43829040',
      '47531338',
      '60731661',
    ],
    product_sku_name: [
      'Mesh Metal Wastebasket in Black',
      'Mesh Metal Wastebasket in Chrome',
      'Mesh Metal Wastebasket in Aqua',
      'The Collection Customized Drapery',
      'smartstuff&trade; Genevieve Convertible Crib in White',
    ],
    product_sub_sub_category: [],
    product_subcategory: [],
    product_url: [
      '/product/mesh-metal-wastebasket/100712?skuId=10217962',
      '/product/mesh-metal-wastebasket/100712?skuId=11170544',
      '/product/mesh-metal-wastebasket/100712?skuId=43829040',
      '/product/the-collection-customized-drapery/3330506?skuId=47531338',
      '/product/smartstuff-trade-genevieve-convertible-crib/3328113?skuId=60731661',
    ],
    registrants_name: 'Feohiaasdf Coupon',
    registry_add_location: 'Registry',
    registry_checklist_completion: '',
    registry_event_date: '05/31/2018',
    registry_favorite_categories_id: [
      '10003',
      '10546',
      '10004',
      '12053',
      '10002',
      'OtherCat-Id',
    ],
    registry_favorite_categories_name: [
      'FINE DINING & GIFTWARE',
      'FURNITURE',
      'HOME DÉCOR',
      'KITCHEN ELECTRICS',
      'BASIC HOUSEWARE',
      'OTHER',
    ],
    registry_id: '543212515',
    registry_product_name_count_purchased: '',
    registry_product_name_count_requested: [],
    registry_purchased: 'Wedding',
    registry_total_items: 14,
    registry_total_value: '',
    registry_type: 'Wedding',
    remove_global_vars: ['language_code'],
    shower_celebration_date: '',
    internal_search_term: 'non-search',
    internal_campaign: 'non-internal campaign',
    merchandising_main_level: 'non-browse',
    merchandising_category: 'non-browse',
    merchandising_subcategory: 'non-browse',
    product_finding_method: 'Registry',
  };
  const emptydata = {
    brand_id: [],
    brand_name: [],
    call_to_actiontype: 'add to registry',
    cart_total_items: 0,
    cart_total_value: '$42',
    category_id: '',
    crossell_page: 'non-cross sell',
    crossell_product: 'non-cross sell',
    customer_postal_code: '20001',
    device_fingerprint: '',
    favorite_store_id: '42',
    inventory_status: [],
    is_ltl_item: [],
    level_of_service: [],
    page_name: 'add to registry',
    page_type: 'Registry',
    pagename_breadcrumb: 'Registry View Page',
    // prettier-ignore
    personalization_type: [],
    product_category: [],
    product_has_personalization: [],
    product_id: [],
    product_image_name: [],
    product_image_url: [],
    product_name: [],
    product_price: [],
    product_quantity: [],
    product_sku_id: [],
    product_sku_name: [],
    product_sub_sub_category: [],
    product_subcategory: [],
    product_url: [],
    registrants_name: 'Feohiaasdf Coupon',
    registry_add_location: 'Registry',
    registry_checklist_completion: '',
    registry_event_date: '05/31/2018',
    registry_favorite_categories_id: [
      '10003',
      '10546',
      '10004',
      '12053',
      '10002',
      'OtherCat-Id',
    ],
    registry_favorite_categories_name: [
      'FINE DINING & GIFTWARE',
      'FURNITURE',
      'HOME DÉCOR',
      'KITCHEN ELECTRICS',
      'BASIC HOUSEWARE',
      'OTHER',
    ],
    registry_id: '543212515',
    registry_product_name_count_purchased: '',
    registry_product_name_count_requested: [],
    registry_purchased: 'Wedding',
    registry_total_items: 14,
    registry_total_value: '',
    registry_type: 'Wedding',
    remove_global_vars: ['language_code'],
    shower_celebration_date: '',
    internal_search_term: 'non-search',
    internal_campaign: 'non-internal campaign',
    merchandising_main_level: 'non-browse',
    merchandising_category: 'non-browse',
    merchandising_subcategory: 'non-browse',
    product_finding_method: 'Registry',
  };
  it("Copy registry on click link 'for category sorting'", () => {
    const expected = gvTealiumInfo(
      itemsData,
      akamiaInfo,
      favStoreInfo,
      registryInfo,
      '1',
      miniCart
    );
    expect(expected).to.deep.equal(actualdata);
  });
  it("Copy registry on click link 'for price sorting'", () => {
    itemsData = {
      inStockCategoryBuckets: [
        {
          items: [
            {
              productURL:
                '/product/mesh-metal-wastebasket/100712?skuId=10217962',
              qtyRemaining: 1,
              purchased: false,
              qtyWebPurchased: 0,
              sKUDetailVO: {
                longDescription:
                  'The attractive Seville Mesh Metal Wastebasket is both stylish and useful. Featuring solid metal bases and sturdy mesh frames, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
                size: '13.4&quot; X 13.4&quot;',
                ecomFulfillment: 'E',
                displayShipMsg:
                  '<a href="/store/static/FreeShipping" class="newOrPopup"><span>\r                      <span class="prod-attrib prod-attrib-free-ship">Free Shipping on Orders Over $29</span> </span> </a>',
                nonShippableStates: [],
                orderToShipSla: '0',
                color: 'BLACK',
                hasSddAttribute: true,
                skuSoldOnline: false,
                onSale: false,
                bopusAllowed: false,
                customizationOffered: false,
                upc: '17641140569',
                vdcSku: false,
                vdcSKUShipMesage: null,
                skuBelowLine: false,
                productSpecs: null,
                shippingRestricted: false,
                customizableCodes: null,
                freeShipMethods: [],
                displayURL: null,
                displayName: 'Mesh Metal Wastebasket in Black',
                altImageList: [],
                emailStockAlertsEnabled: true,
                shipMsgFlag: true,
                giftWrapEligible: true,
                inCartFlag: false,
                activeFlag: true,
                assemblyTime: '0',
                webOfferedFlag: true,
                skuInStock: false,
                disableFlag: false,
                restrictedForBopusAllowed: false,
                skuImages: {
                  largeImage: '60664210217962p?$478$',
                  mediumImage: '60664210217962p?$146$',
                  zoomImage: null,
                  zoomImageIndex: 0,
                  basicImage: '60664210217962p',
                  collectionThumbnailImage: null,
                  thumbnailImage: '60664210217962p?$83$',
                  altImageList: [],
                  smallImage: '60664210217962p?$146$',
                  anywhereZoomAvailable: false,
                  swatchImage: '1762100712s',
                  regularImage: null,
                },
                ltlItem: false,
                intlRestricted: false,
                skuId: '10217962',
                eligibleRebates: [],
                customizeCTAFlag: null,
                bopusExcludedForMinimalSku: false,
                customizableRequired: false,
                pricingLabelCode: null,
                parentProdId: '100712',
                description:
                  'The attractive Seville Mesh Metal Wastebasket is both stylish and useful. Featuring solid metal bases and sturdy mesh frames, this new take on a classic design is the perfect addition to your bedroom, bathroom, or home office.',
                restrictedForIntShip: false,
                skuGiftCard: false,
                hasRebate: false,
                taxStatus: '01',
                personalizationType: 'N',
                dynPriceInfoAlreadyFetched: false,
                vdcOffsetMessage: null,
                eligibleShipMethods: [],
              },
              jdaCatId: '10002',
              itemType: '',
              qtyPurchased: 0,
              formattedPrice: '$11.99',
              assemblyFees: 0,
              refNum: null,
              ephCatId: '',
              colorDesc: null,
              formattedPriceVal: '$11.99',
              formattedDeliverySurcharge: '$0',
              priceVal: 11.99,
              qtyRequested: 1,
              shipMethodUnsupported: false,
              productDescrip: null,
              formattedInCartPriceVal: '',
              jdaCatName: 'BASIC HOUSEWARE',
              createTimestamp: null,
              deptSortSeq: 0,
              markedAsFav: false,
              sku: 10217962,
              formattedPersonalizedPrice: '',
              inCartPriceVal: null,
              jdaRetailPrice: 0,
            },
          ],
        },
      ],
    };
    const expected = gvTealiumInfo(
      itemsData,
      akamiaInfo,
      favStoreInfo,
      registryInfo,
      '2',
      miniCart
    );
    expect(expected).to.deep.equal({
      brand_id: [],
      brand_name: [],
      call_to_actiontype: 'add to registry',
      cart_total_items: 0,
      cart_total_value: '$42',
      category_id: '',
      crossell_page: 'non-cross sell',
      crossell_product: 'non-cross sell',
      customer_postal_code: '20001',
      device_fingerprint: '',
      favorite_store_id: '42',
      inventory_status: ['out of stock'],
      is_ltl_item: [false],
      level_of_service: [''],
      page_name: 'add to registry',
      page_type: 'Registry',
      pagename_breadcrumb: 'Registry View Page',
      // prettier-ignore
      personalization_type: [ undefined],
      product_category: [],
      product_has_personalization: ['false'],
      product_id: ['100712'],
      product_image_name: ['Mesh Metal Wastebasket in Black'],
      product_image_url: ['60664210217962p?$146$'],
      product_name: ['Mesh Metal Wastebasket in Black'],
      product_price: [11.99],
      product_quantity: [1],
      product_sku_id: ['10217962'],
      product_sku_name: ['Mesh Metal Wastebasket in Black'],
      product_sub_sub_category: [],
      product_subcategory: [],
      product_url: ['/product/mesh-metal-wastebasket/100712?skuId=10217962'],
      registrants_name: 'Feohiaasdf Coupon',
      registry_add_location: 'Registry',
      registry_checklist_completion: '',
      registry_event_date: '05/31/2018',
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_purchased: 'Wedding',
      registry_total_items: 14,
      registry_total_value: '',
      registry_type: 'Wedding',
      remove_global_vars: ['language_code'],
      shower_celebration_date: '',
      internal_search_term: 'non-search',
      internal_campaign: 'non-internal campaign',
      merchandising_main_level: 'non-browse',
      merchandising_category: 'non-browse',
      merchandising_subcategory: 'non-browse',
      product_finding_method: 'Registry',
    });
  });
  it("Copy registry on click link 'for price sorting when inStockCategoryBuckets is blank", () => {
    itemsData = {
      inStockCategoryBuckets: [{}],
    };
    const expected = gvTealiumInfo(
      itemsData,
      akamiaInfo,
      favStoreInfo,
      registryInfo,
      '2',
      miniCart
    );
    expect(expected).to.deep.equal({
      brand_id: [],
      brand_name: [],
      call_to_actiontype: 'add to registry',
      cart_total_items: 0,
      cart_total_value: '$42',
      category_id: '',
      crossell_page: 'non-cross sell',
      crossell_product: 'non-cross sell',
      customer_postal_code: '20001',
      device_fingerprint: '',
      favorite_store_id: '42',
      inventory_status: [],
      is_ltl_item: [],
      level_of_service: [],
      page_name: 'add to registry',
      page_type: 'Registry',
      pagename_breadcrumb: 'Registry View Page',
      // prettier-ignore
      personalization_type: [ ],
      product_category: [],
      product_has_personalization: [],
      product_id: [],
      product_image_name: [],
      product_image_url: [],
      product_name: [],
      product_price: [],
      product_quantity: [],
      product_sku_id: [],
      product_sku_name: [],
      product_sub_sub_category: [],
      product_subcategory: [],
      product_url: [],
      registrants_name: 'Feohiaasdf Coupon',
      registry_add_location: 'Registry',
      registry_checklist_completion: '',
      registry_event_date: '05/31/2018',
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_purchased: 'Wedding',
      registry_total_items: 14,
      registry_total_value: '',
      registry_type: 'Wedding',
      remove_global_vars: ['language_code'],
      shower_celebration_date: '',
      internal_search_term: 'non-search',
      internal_campaign: 'non-internal campaign',
      merchandising_main_level: 'non-browse',
      merchandising_category: 'non-browse',
      merchandising_subcategory: 'non-browse',
      product_finding_method: 'Registry',
    });
  });
  it("Copy registry on click link 'for date sorting else'", () => {
    itemsData = {};
    const expected = gvTealiumInfo(
      itemsData,
      akamiaInfo,
      favStoreInfo,
      registryInfo,
      '3',
      miniCart
    );
    expect(expected).to.deep.equal(emptydata);
  });
  it("Copy registry on click link 'for date sorting'", () => {
    const expected = gvTealiumInfo(
      itemsData,
      akamiaInfo,
      favStoreInfo,
      registryInfo,
      '3',
      miniCart
    );
    expect(expected).to.deep.equal(actualdata);
  });

  it('sort option by date when registryItemList is empty', () => {
    const actualData = {
      brand_id: [],
      brand_name: [],
      call_to_actiontype: 'add to registry',
      cart_total_items: 0,
      cart_total_value: '$42',
      category_id: '',
      crossell_page: 'non-cross sell',
      crossell_product: 'non-cross sell',
      customer_postal_code: '20001',
      device_fingerprint: '',
      favorite_store_id: '42',
      inventory_status: [],
      is_ltl_item: [],
      level_of_service: [],
      page_name: 'add to registry',
      page_type: 'Registry',
      pagename_breadcrumb: 'Registry View Page',
      // prettier-ignore
      personalization_type: [ ],
      product_category: [],
      product_has_personalization: [],
      product_id: [],
      product_image_name: [],
      product_image_url: [],
      product_name: [],
      product_price: [],
      product_quantity: [],
      product_sku_id: [],
      product_sku_name: [],
      product_sub_sub_category: [],
      product_subcategory: [],
      product_url: [],
      registrants_name: 'Feohiaasdf Coupon',
      registry_add_location: 'Registry',
      registry_checklist_completion: '',
      registry_event_date: '05/31/2018',
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_purchased: 'Wedding',
      registry_total_items: 14,
      registry_total_value: '',
      registry_type: 'Wedding',
      remove_global_vars: ['language_code'],
      shower_celebration_date: '',
      internal_search_term: 'non-search',
      internal_campaign: 'non-internal campaign',
      merchandising_main_level: 'non-browse',
      merchandising_category: 'non-browse',
      merchandising_subcategory: 'non-browse',
      product_finding_method: 'Registry',
    };
    itemsData = fromJS([
      {
        catSeoUrl: null,
        categoryId: '10002_BASICHOUSEWARE',
        displayName: 'BASIC HOUSEWARE',
        recommandedLinks: null,
        recommendedCatFlag: false,
        registryItemList: undefined,
      },
    ]);

    const expected = gvTealiumInfo(
      itemsData,
      akamiaInfo,
      favStoreInfo,
      registryInfo,
      '3',
      miniCart
    );
    expect(actualData).to.deep.equal(expected);
  });

  it('sort option by category when registryItemList is empty', () => {
    const actualData = {
      brand_id: [],
      brand_name: [],
      call_to_actiontype: 'add to registry',
      cart_total_items: 0,
      cart_total_value: '$42',
      category_id: '',
      crossell_page: 'non-cross sell',
      crossell_product: 'non-cross sell',
      customer_postal_code: '20001',
      device_fingerprint: '',
      favorite_store_id: '42',
      inventory_status: [],
      is_ltl_item: [],
      level_of_service: [],
      page_name: 'add to registry',
      page_type: 'Registry',
      pagename_breadcrumb: 'Registry View Page',
      // prettier-ignore
      personalization_type: [ ],
      product_category: [],
      product_has_personalization: [],
      product_id: [],
      product_image_name: [],
      product_image_url: [],
      product_name: [],
      product_price: [],
      product_quantity: [],
      product_sku_id: [],
      product_sku_name: [],
      product_sub_sub_category: [],
      product_subcategory: [],
      product_url: [],
      registrants_name: 'Feohiaasdf Coupon',
      registry_add_location: 'Registry',
      registry_checklist_completion: '',
      registry_event_date: '05/31/2018',
      registry_favorite_categories_id: [
        '10003',
        '10546',
        '10004',
        '12053',
        '10002',
        'OtherCat-Id',
      ],
      registry_favorite_categories_name: [
        'FINE DINING & GIFTWARE',
        'FURNITURE',
        'HOME DÉCOR',
        'KITCHEN ELECTRICS',
        'BASIC HOUSEWARE',
        'OTHER',
      ],
      registry_id: '543212515',
      registry_product_name_count_purchased: '',
      registry_product_name_count_requested: [],
      registry_purchased: 'Wedding',
      registry_total_items: 14,
      registry_total_value: '',
      registry_type: 'Wedding',
      remove_global_vars: ['language_code'],
      shower_celebration_date: '',
      internal_search_term: 'non-search',
      internal_campaign: 'non-internal campaign',
      merchandising_main_level: 'non-browse',
      merchandising_category: 'non-browse',
      merchandising_subcategory: 'non-browse',
      product_finding_method: 'Registry',
    };
    itemsData = fromJS([
      {
        catSeoUrl: null,
        categoryId: '10002_BASICHOUSEWARE',
        displayName: 'BASIC HOUSEWARE',
        recommandedLinks: null,
        recommendedCatFlag: false,
        registryItemList: undefined,
      },
    ]);

    const expected = gvTealiumInfo(
      itemsData,
      akamiaInfo,
      favStoreInfo,
      registryInfo,
      '1',
      miniCart
    );
    expect(actualData).to.deep.equal(expected);
  });
});
/* eslint-enable max-lines */
