export const REGISTRY_QUICK_ADD = 'REGISTRY_QUICK_ADD';
export const REGISTRY_QUICK_ADD_CLOSED = 'registryQuickAddClosed';

export const FETCH_REGISTRY_QUICK_ADD_ITEMS = 'FETCH_REGISTRY_QUICK_ADD_ITEMS';
export const FETCH_REGISTRY_QUICK_ADD_ITEMS_SUCCESS =
  'FETCH_REGISTRY_QUICK_ADD_ITEMS_SUCCESS';
export const FETCH_REGISTRY_QUICK_ADD_ITEMS_ERROR =
  'FETCH_REGISTRY_QUICK_ADD_ITEMS_ERROR';
export const REGISTRY_OWNER_STATE_KEY = 'RegistryOwner';
export const QUICK_ADD_TILE_COUNT = 'maxRegQuickAddTileCount';
export const QUICK_ADD_TILE_COUNT_VARIATION_B =
  'maxRegQuickAddTileCountVariationB';
