export const SIGN_IN_USER = 'BBB/REGISTRY/SIGN_IN_USER';
export const SIGN_IN_USER_SUCCESS = 'BBB/REGISTRY/SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_ERROR = 'BBB/REGISTRY/SIGN_IN_USER_ERROR';

export const RECOGNIZED_USER_SIGNIN_KEY = 'tymRecgonizedUser';
