export const REPLACE_PRODUCT_FROM_REGISTRY =
  'BBB/REPLACE_PRODUCT_FROM_REGISTRY/REPLACE_PRODUCT_FROM_REGISTRY';

export const REPLACE_PRODUCT_FROM_REGISTRY_SUCCESS =
  'BBB/REPLACE_PRODUCT_FROM_REGISTRY/REPLACE_PRODUCT_FROM_REGISTRY_SUCCESS';

export const REPLACE_PRODUCT_FROM_REGISTRY_ERROR =
  'BBB/REPLACE_PRODUCT_FROM_REGISTRY/REPLACE_PRODUCT_FROM_REGISTRY_ERROR';

export const REPLACE_PRODUCT_FROM_REGISTRY_KEY = 'ReplaceProductFromRegistry';
