import { registryState } from '../OptInModalRegistryData';

describe(__filename, () => {
  const registryDetailsData = {
    coRegistrantEmail: 'Regrlvtestone',
    coRegistrantFirstName: 'Regrlvtestone',
    coRegistrantLastName: 'User',
    coRegBG: 'abc',
    coRegOwner: 'bcd',
    college: undefined,
    eventDate: '11/30/2021',
    eventVO: {
      babyGender: 'S~||S~',
      babyNurseryTheme: '',
      showerDate: '',
      guestCount: '2',
    },
    babyGender: 'S~||S~',
    futureShippingAddress: undefined,
    futureShippingDate: '',
    gender: 'amle',

    networkAffiliation: '',
    isPublic: '1',
    primaryRegistrantEmail: 'TESTTOOLTIP1307@YOPMAIL.COM',
    primaryRegistrantFirstName: 'Regrlvtestone',
    primaryRegistrantLastName: 'User',
    primaryRegistrantMaidenName: 'abc',
    primaryRegistrantMobileNum: '1111111111',
    primaryRegistrantPrimaryPhoneNum: '9999999999',
    shippingAddress: {
      addressLine1: '112 OCEAN AVE',
      addressLine2: 'new york',
      city: 'AMITYVILLE',
      company: 'bed',
      country: 'NA',
      firstName: 'Regrlvtestone',
      lastName: 'User',
      primaryPhone: '9999999999',
      qasValidated: false,
      state: 'NY',
      zip: '5678',
    },
    state: 'NY ',
    prefStoreNum: '89',
  };
  it('registryDetailsData on present utag data', () => {
    const expected = registryState(registryDetailsData);
    expect(expected).to.deep.equal({
      shippingCity: 'AMITYVILLE',
      primaryPh: '9999999999',
      shippingState: 'NY',
      shippingZip: '5678',
      addressOne: '112 OCEAN AVE',
      apartment: 'new york',
      isPublic: '1',
      babyGender: 'S~||S~',
      babyMaidenName: 'abc',
      babyNurseryTheme: '',
      city: 'AMITYVILLE',
      coEmail: '',
      coFirstName: 'Regrlvtestone',
      coGender: 'abc',
      coLastName: 'User',
      coRegOwner: 'bcd',
      college: undefined,
      mobilePh: '1111111111',
      firstName: 'Regrlvtestone',
      lastName: 'User',
      prefStoreNum: '89',
      state: 'NY',
      zip: '5678',
      qasContactValidated: false,
      shippingAddressOne: '112 OCEAN AVE',
      shippingApartment: 'new york',
      shippingCountry: undefined,
      qasShippingValidated: false,
      moveInAddressOne: undefined,
      moveInApartment: 'new york',
      moveInCity: 'AMITYVILLE',
      moveInState: 'NY',
      moveInCountry: 'NA',
      qasMovingValidated: false,
      moveInZip: '5678',
      futureShippingDate: '',
      email: 'TESTTOOLTIP1307@YOPMAIL.COM',
      thirdPartySelected: '',
      guests: '2',
      eventDate: '11/30/2021',
      showerDate: '',
      gender: 'S~||S~',
      isContactAddressChanged: false,
      isMovingSoonChanged: true,
      coRegProfileStatus: 'false',
      iscoRegEmailFlag: false,
      shippingStreet: true,
      showShippingInfo: true,
      showMoveInInfo: undefined,
    });
  });
});
