export const CONTRIBUTE_CASH_FUND_STATE_KEY = 'contributeCashFundKey';
export const CONTRIBUTE_CASH_FUND = 'CONTRIBUTE_CASH_FUND';
export const CONTRIBUTE_CASH_FUND_SUCCESS = 'CONTRIBUTE_CASH_FUND_SUCCESS';
export const CONTRIBUTE_CASH_FUND_ERROR = 'CONTRIBUTE_CASH_FUND_ERROR';
export const CLEAR_CONTRIBUTE_CASH_FUND = 'CLEAR_CONTRIBUTE_CASH_FUND';
export const DEFAULT_ERROR_MESSAGE = 'response is not correct';
